### ISSUE TITLE
Example code incorrectly matches email against 'name' rather than 'login'

### ISSUE THREAD

**Issue by jmuncaster** [box/box-node-sdk#105]
On this line:
https://github.com/box/box-node-sdk/blob/master/examples/app-auth/index.js#L113

The code is verifying that the 'email' form field matches the 'name' value of the response.

When I ran this code, I got 'login' as a response field, not 'name'

Changing the test to 'login' seemed to fix it.

**Comment by mattwiller** [comment]
@jmuncaster I just tried running the sample app, and it runs correctly for me; can you show me the exact error you're seeing?

The sample app uses the `name` field on the User object to store the email address they signed up with — the `login` field for App Users is populated by Box and isn't really useful for the sample application.
