### ISSUE TITLE
adminAPIClient.enterprise.addAppUser is not a function

### ISSUE THREAD

**Issue by ChristianLuxem** [box/box-node-sdk#108]
Hello together,

i am trying to do an Integration of Box into the collaboration platform IBM Connections. I am using your SDK and i am trying to authenticate on my created app, to show the content of a folder. 
So i am using the following code:
```
sdk = new BoxSDK({
	    clientID: CLIENT_ID,
	    clientSecret: CLIENT_SECRET,
	    appAuth: {
	        keyID: PUBLIC_KEY_ID,
	        privateKey: PRIVATE_KEY,
	        passphrase: PASSPHRASE
	    }
	});
	var adminAPIClient = sdk.getAppAuthClient('enterprise', ENTERPRISE_ID);
```
First Question on that:  my PRIVATE_KEY const is declared with the following code:
`const PRIVATE_KEY = fs.readFileSync('private_key.pem');`
Is that correct? I miss a part in the documentation where the variables are explained... 
If you would explain it to me, i would check it in...

Now i try to get all users from my App and if there is no user, i try to create an app user (because i will need the app user to get the content of the root folder, right?):

```
function getUsers() {
		var userCreated = false;
		adminAPIClient.enterprise.getUsers(null, function(response) {
			console.log("Enterprise getUsers: " + response); // return is null...
			if (!response && !userCreated) {
				console.log("No User found --> create AppUser");
				userCreated = true;
				adminAPIClient.enterprise.addAppUser('XCC AppUser',{
				        job_title: 'Showing Files',
				    },
				 	function done (data) {
				 		console.log("User created - Now trying to get the Users!");
				 		console.log("Return of addAppUser: " + data);
				 		getUsers();
				 	}
				);
			}
		});
	}
```

Nodejs is throwing an error: adminAPIClient.enterprise.addAppUser is not a function
i was looking at the following documentation: 
https://github.com/box/box-node-sdk/blob/master/docs/enterprise.md

So what am i doing wrong and can you get me into the right direction?
That would be great, thanks!

**Comment by mself** [comment]
The `addAppUser()` function was added ver recently.  Perhaps you need to do `npm update` to get the latest SDK code?

**Comment by mself** [comment]
You might also look at the sample app at https://github.com/box/samples/tree/master/box-node-lambda-sample for an example of loading the private key.  You can read it from a file or just use a string literal in your code.  The "Next steps" section of the sample app also has some code snippets for creating and using app users.  Good luck!

**Comment by mattwiller** [comment]
@ChristianLuxem @mself The addAppUser() was just added, and is not yet released in any version of the SDK; we'll be cutting a release within the next few weeks with a few new features, including that function.  Until that time, you should be able to create app users with the existing function like this:

```js
client.enterprise.addUser(
    null,
    'XCC AppUser',
    {
        is_platform_access_only: true,
        job_title: 'Showing Files'
    },
    callback
);
```

**Comment by ChristianLuxem** [comment]
Thank you! I will close it.
