### ISSUE TITLE
Intermittent "auth code or refresh token expired"/"Expired Auth: Auth code or refresh token has expired" error with App Auth client at v1.3.0

### ISSUE THREAD

**Issue by neocolmartin** [box/box-node-sdk#109]
This looks like the same problem as #96, but I've seen it at v1.2.0 and v1.3.0.

This is the code that is producing the error:

```Javascript
 sdk.folders.getItems(req.params.folderId, null, (err, data) => {
    if (err) {
      console.log(`An error occurred - ${err.message}`);
      return res.status(500).send(err);
    }
    console.log(`All good -  ${data.id}`);
    return res.status(200).json(data);
  });
```

This is the output I get on the console:
```
An error occurred - Expired Auth: Auth code or refresh token has expired.
```

The client that is receiveing the response from `res.status(500).send(err)` receives this (certain bits omitted here for brevity):
```json
{
  "statusCode":400,
  "response":{
    "statusCode":400,
    "body":{
      "error":"invalid_grant",
      "error_description":"Current date/time MUST be before the expiration date/time listed in the 'exp' claim"
    },
    "headers": ...,
    "request":{
      "uri":{
        ...
        "href":"https://api.box.com/oauth2/token"
      },
      "method":"POST",
      "headers": ...
    }
  },
  "authExpired":true
}
```

To start with, it appeared that restarting node stopped the error occurring for a while. But now it's occurring all the time.

**Comment by mattwiller** [comment]
@neocolmartin If the `exp` claim is failing like this, it generally means that your server's clock is significantly off from Box's servers'.  Since the `exp` claim is computed on your server as `exp = yourServerTimestamp + expirationTime` (expirationTime is a configuration option in the SDK, and is 60 seconds by default), and on the Box server we check that `boxServerTimestamp < exp`, it's important that your server and Box's have similar times.

To validate, could you please confirm that your server's timestamp matches the current Unix time at https://www.epochconverter.com/ for me?  You should be able to run `date -u +%s` on your server to get the current UTC timestamp and compare it to what is "current".

**Comment by neocolmartin** [comment]
Thanks @mattwiller.
Right now my machine is a few seconds behind, but the calls to the Box SDK are successful at the moment. If they fail again I'll check the timestamp again.

**Comment by neocolmartin** [comment]
I'm still seeing this issue, and my system's clock is at most 1 second out from epochconverter.com.

2 questions:

1. To change the expiration time (in the hope of making this less likely to occur), do I create my Box SDK with something like this (the `expiredBufferMS` line is the only line that's new):

  ```
const sdk = new BoxSDK({
    clientID: process.env.CLIENT_ID,
    clientSecret: process.env.CLIENT_SECRET,
    expiredBufferMS: 30000,
    appAuth: {
      keyID: process.env.PUBLIC_KEY_ID,
      privateKey: fs.readFileSync(path.resolve(__dirname, process.env.PRIVATE_KEY_PATH)),
      passphrase: process.env.PRIVATE_KEY_PASSPHRASE,
    },
  });
```

2. Does this suggest that there might be a problem either with the SDK or with your servers that might require further investigation? If so, is there more information that I can provide that would be useful?

**Comment by mattwiller** [comment]
@neocolmartin You could try increasing the JWT token expiration time parameter like so:

```js
const sdk = new BoxSDK({
  clientID: process.env.CLIENT_ID,
  clientSecret: process.env.CLIENT_SECRET,
  appAuth: {
    keyID: process.env.PUBLIC_KEY_ID,
    privateKey: fs.readFileSync(path.resolve(__dirname, process.env.PRIVATE_KEY_PATH)),
    passphrase: process.env.PRIVATE_KEY_PASSPHRASE,
    expirationTime: 120 // <------ Increase this value to something above default of 60
  },
});
```

The [API docs](https://docs.box.com/docs/app-auth#section-6-constructing-the-claims) indicate that the maximum value is 60, but if there's a clock issue maybe setting it longer will help.  Note that setting these JWT tokens to be long-lived is less secure (in theory someone could intercept the token and use it), so it's not an ideal solution.

If you don't mind giving me some more information about your specific requests, I can also try to debug a bit on the Box side.  If possible, could you provide the following details?

* The version of the SDK you're using
* The exact time a request that failed was made (on your system clock, e.g. via `Date.now()`)
* The error response headers (`error.response.headers`)

**Comment by neocolmartin** [comment]
Thanks @mattwiller 

* The version of the SDK I'm using: Inside my project, the `node_modules/box-node-sdk/package.json` file identifies itself as `"version": "1.3.0"`.

The error isn't occurring right now, but I've added the logging in now to capture `Date.now()` and the response headers so I can report them next time it happens.

**Comment by neocolmartin** [comment]
@mattwiller  I've seen the problem again and here is the data you asked for:

* The version of the SDK I'm using: Inside my project, the `node_modules/box-node-sdk/package.json` file identifies itself as `"version": "1.3.0"`.
* My app made 3 requests (all using the same `BoxSDK` object, but each calling `getAppAuthClient` separately). The 3 timestamps at which the calls were made were: `1488891473344`, `1488891473856`, and `1488891474067`. All three returned an error response ("Current date/time MUST be before the expiration date/time listed in the 'exp' claim"), the first response was received at `1488891474481`.
* I'll send you the headers directly.

**Comment by neocolmartin** [comment]
Right, at the moment my machine's time was wrong. I'm not sure if it was wrong previously or not as I was getting confused by epochconverter.com, which I thought was showing me time from their server, but was actually showing me time from my browser. I'll check again whether the API calls work when I get a chance after having changed the time.

**Comment by mattwiller** [comment]
@neocolmartin Yeah, I'm definitely seeing some disagreement between the clocks.  Your request and response are ~1 second apart, so clearly the issue is not that the token is expiring en route to Box.  For reference, I'm seeing that the request you made (based on the headers you sent me) was handled by the Box servers at a timestamp of `1488892021`, which is over 9 minutes off from your system's clock.

**Comment by kabirbaidhya** [comment]
Hi I'm getting this error in my application now which is already. I've gone through all the related issues in this repository but still can't fix this error. 

```
Expired Auth: Auth code or refresh token has expired.
at Object.buildResponseError (/source/node-api/node_modules/box-node-sdk/lib/util/errors.js:57:23)
at Object.buildExpiredAuthError (/source/node-api/node_modules/box-node-sdk/lib/util/errors.js:70:28)
at /source/node-api/node_modules/box-node-sdk/lib/token-manager.js:211:21
at /source/node-api/node_modules/box-node-sdk/lib/api-request.js:285:3
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)

```
I'm using `getAppAuthClient` to get the client as we're using `enterpriseId` to authenticate with the box.

In my code I've done this:
```javascript
const config = {
    box: {
        clientID: process.env.BOX_CLIENT_ID,
        clientSecret: process.env.BOX_CLIENT_SECRET,
        appAuth: {
            keyID: process.env.BOX_APP_AUTH_KEY_ID,
            privateKey: fs.readFileSync(process.env.BOX_APP_AUTH_PRIVATE_KEY_FILE || defaultPrivateKeyPath),
            passphrase: process.env.BOX_APP_AUTH_PASSPHRASE
        },
        enterpriseId: process.env.BOX_ENTERPRISE_ID
    }
   ...
}
```
```javascript
    let sdk = new BoxSDK(config.box);
    let client = sdk.getAppAuthClient('enterprise', config.box.enterpriseId);

    logger.info('Getting the list of files from the box');

    return new Promise((resolve, reject) => {
        client.folders.getItems(ROOT_FOLDER, {
            fields: 'name,id',
            offset: 0,
            limit: config.fileRetrievalLimit
        }, (err, result) => {
            if (err) {
                logger.error('Error fetching the list', err);
                reject(err);
                return;
            }

            logger.info('Got the file list');
            logger.debug('Results', result);

            resolve(result);
        });
    });
```


If anyone can suggest some workaround to fix this problem it would be really appreciated. 

I'm using  version `1.3.0` too.

**Comment by kabirbaidhya** [comment]
BTW, I'm just trying to debug this stuff. And seems like the response I received is:

`400` and `{"error":"invalid_grant","error_description":"Please check the 'exp' claim."}`

Not sure what this means. But I'm wondering how this error suddenly came up while everything was working pretty fine few days ago.

**Comment by kabirbaidhya** [comment]
@mattwiller I've tried setting the `expirationTime` as you've described above as well. Still no luck. 

You can check my error response above. Thanks.

**Comment by neocolmartin** [comment]
@kabir, somewhere in the error object you should have access to the HTTP response that was sent by the server. My advice would be to find the “Date” header in there and compare it with the date on your system when the request was sent (adjusting for timezones if needed). If there’s much difference, then that will cause the request to get rejected with this error. (Comparing the local time to the Date response header proved a better check for me than comparing the local time to anything else).

If they differ, then the solution as mentioned above is to adjust your system’s clock to match the Box server’s one.

**Comment by kabir** [comment]
@neocolmartin I think you have the wrong Kabir

**Comment by neocolmartin** [comment]
My apologies.
That should have been @kabirbaidhya

**Comment by mattwiller** [comment]
@kabirbaidhya The App Auth client does attempt to automatically refresh tokens using the JWT grant, but the error object you posted suggests exactly what @neocolmartin mentioned: your client's time is almost certainly significantly different from Box's server time and thus the `exp` claims that it generates are already expired by the time the JWT is processed by Box's servers.  You might try to synchronize the time on your client to an established time authority (such as ntp) to avoid this issue.

**Comment by kabirbaidhya** [comment]
Okay, that makes sense. Thanks @mattwiller and @neocolmartin.
