### ISSUE TITLE
Errors on node v0.12.7

### ISSUE THREAD

**Issue by cruxdyno** [box/box-node-sdk#11]
We have some old code using node 0.12.7, and I needed this library there.  I patched it and made all the tests pass.  I'll submit a pull request if you like, but I assume you want to continue with ECMA6.

https://github.com/MobileDay/box-node-sdk/tree/node_v0.12.7

Here are some of the errors I saw:
SyntaxError: Unexpected token =>
box-client.js:238-239 undefined is not a function (Object.assign)

**Comment by mattwiller** [comment]
Since 0.12 is going to be unsupported by the end of this year (https://github.com/nodejs/LTS), we aren't planning on maintaining support for it at this time.  That said, we can keep an eye on it and re-evaluate if there's a lot of demand for backwards compatibility.
