### ISSUE TITLE
Feature request: Use server timestamp to generate exp claim

### ISSUE THREAD

**Issue by neocolmartin** [box/box-node-sdk#115]
I would like to request a feature (or to ask for input on whether a pull request for this feature would be likely to be accepted). The feature would be this: when a token request fails with the error "`Current date/time MUST be before the expiration date/time listed in the 'exp' claim`", then the SDK would take the "Date" header form the response, and generate a new `exp` claim using the Date header's value as the current timestamp, in an effort to generate an `exp` claim that is correct relative to the Box server's timestamp.

This is in an attempt to avoid the problem discussed in #109 when the clocks are not synchronised between the client machine and Box's server.

One downside of this is that the error keyword (`invalid_grant`) is not specific to the `exp` claim. So either the SDK would have to do this for all `invalid_grant` errors (or at least it would check for mismatched timestamps whenever it receives an `invalid_grant` error & only retry if it finds they're out of sync), or it would have to inspect the `error_description`, which is probably not a reliable thing to do.

(There are alternative approaches that could be taken to address that problem, such as moving the generation of the `exp` claim entirely onto Box's server, but that would be a more fundamental change in the API.)

Is this something that would make sense in this project, or would it be out of place?

**Comment by mattwiller** [comment]
@neocolmartin Thanks for the suggestion!  I'm following up with the team to see how feasible it would be to support retrying with an `exp` claim based on the server's `Date` header.
