### ISSUE TITLE
400 Bad Request when trying to use the example app

### ISSUE THREAD

**Issue by joemidi** [box/box-node-sdk#12]
I get the following error when I try and use the example app:

`An error occurred during login - Unexpected API Response [400 Bad Request]`

It gives me no information further than that.

I've added all the app credentials in the `examples/app-auth/index.js` file.

**Comment by mattwiller** [comment]
@joemidi You can add something like `console.log(err);` at https://github.com/box/box-node-sdk/blob/master/examples/app-auth/index.js#L101 to get more information about the error.  I'll update the sample app later to include more error details on the page, but in the meantime you should be able to log it yourself.

**Comment by trantor-saurabh-barthwal** [comment]
I am also getting the same issue. Help me for the same.

**Comment by mattwiller** [comment]
@trantor-saurabh-barthwal As noted above, you should be able to modify the sample app code to get more information about the error — I recommend logging `err.response.body` to see if there's more information from the API about what's going on.  One common problem is that your app may not be authorized by your enterprise administrator.  If you haven't already, you may need to contact your enterprise admin and send them the API key of your application so they can authorize it in your enterprise's settings.
