### ISSUE TITLE
adminAPIClient.users.addEmailAlias adds an alias but is not confirmed

### ISSUE THREAD

**Issue by kendomen** [box/box-node-sdk#128]
adminAPIClient.users.addEmailAlias adds an email alias but it's not confirmed so it doesn't show up in 
adminAPIClient.users.getEmailAliases()
nor can I update a user's login to the new alias.

the code in users.js I think should set is_confirmed to true.

In box .net sdk, it sets is_confirmed to true.

**Comment by kendomen** [comment]
`
// --------------------------------------------------------------------------
//  To change a user's primary login, do method calls 1-4 below
//
// Note:  Changed box-node-sdk users.js addEmailAlias to set is_confirmed to true.
//        Having it set to false was causing the the next call to 
//        update the user with the new login to fail.  
//        box .net sdk sets is_confirmed to true 
//        so I'm not sure why box-node-sdk sets it to false.
// --------------------------------------------------------------------------

// 1.  Add new emailAlias
adminAPIClient.users.addEmailAlias(userId, newEmail, function (err, newAlias) {
    if (err) {
       console.log("403 is a non-meaningful error for email already used.");
    }
    else {        
        // 2.  update user login with new email alias.  This makes the former login an email alias 
        adminAPIClient.users.update(userId, {login: newEmail}, function (err, updatedUser) {                    
            console.log(updatedUser);                                   
            
            // 3.  get the last emailAlias for this user which equals former login
            adminAPIClient.users.getEmailAliases(userId, function (err, emailAliases) {       
                var emailAliasId = emailAliases.entries[emailAliases.entries.length -1].id;
                
                // 4.  remove the last emailAlias
                adminAPIClient.users.removeEmailAlias(userId, emailAliasId, function (err, cleanedUpUser) {
                    
                    // 5.  verify emailAliases look good
                    adminAPIClient.users.getEmailAliases(userId, function (err, updatedEmailAliases) { 
                        updatedEmailAliases.entries.forEach(function(emailAlias) {
                            console.log(emailAlias);
                        }, this);
                    });    
                });
            });
        });    
    } 
});
`

**Comment by djordan** [comment]
Thanks @kendomen - we have a new SDK release in the works, so we'll see if we can get this addressed along with it.

**Comment by mattwiller** [comment]
@kendomen Making the change outright would be a breaking change, so we won't be able to confirm by default.  However, I've added an option to confirm the alias:

```js
client.users.addEmailAlias(userID, newEmail, {is_confirmed: true}, function(err, alias) { /* handle the added alias */});
```
