### ISSUE TITLE
SDK Client using BOX Token only

### ISSUE THREAD

**Issue by divinann** [box/box-node-sdk#130]
Currently, I dont have the client ID and client secret information to create SDK object. 

I was wondering similiar to BOX SDK Java, where you just need BOX Token to make API call. Is it possible to do the same for Nodejs.

**Comment by KarthikShanmugasundaram** [comment]
@divinann client ID and client secret are mandatory to create the SDK instance in Node.js. A token cannot be created without a client app. If you have the client app, the client id and client secret must be present. Could you please clarify why you dont have those?

**Comment by divinann** [comment]
In our organization, we have to use an API Gateway solution to retrieve the BOX Token so they can track the BOX API usage. The organization doesn't want to share the client secret with us. If shared, i would bypass the API Gateway and metrics wont be collected for my application.

I noticed that in Java SDK, client ID and secret is not needed to make API calls. I was hoping we can do the same here as well

**Comment by KarthikShanmugasundaram** [comment]
@divinann When you use sdk.getBasicClient you dont need real client_id and client_secret values. 
var sdk = new BoxSDK({
       clientID: 'client_id',
       clientSecret: 'client_secret'
});

var client = sdk.getBasicClient('kTK9k8iKiYHK58PJdbHr0qaDjn5vzbX0');

We will process you request based on priority as we have provided the work around.

**Comment by divinann** [comment]
Got it. Is there a way to specify proxy to make these BOX API calls?

When i invoke any API, i get an error message. See attached file.
![proxy issue](https://cloud.githubusercontent.com/assets/18354730/26087552/621906f6-39bf-11e7-8f35-14b7871a5094.png)

**Comment by KarthikShanmugasundaram** [comment]
var sdk = new BoxSDK({
    apiRootURL: 'https://proxy_url1',
    uploadAPIRootURL: 'https://proxy_url2',
    clientID: 'client_id',
    clientSecret: 'client_secret'
});

@divinann replace the proxy urls

**Comment by divinann** [comment]
@KarthikShanmugasundaram 

I did that. I got a different error message - socket hang up.
Am i supposed to putting a proxy URL in those attributes? By looking at the attribute name, it is expecting a BOX API url not proxy url.

**Comment by divinann** [comment]
@KarthikShanmugasundaram 

As discussed, let me know if you find any alternative to pass proxy url to the SDK library.

**Comment by mattwiller** [comment]
@divinann If your API Gateway acts as a tunneling proxy, you can specify this in the SDK config:

```js
var sdk = new BoxSDK({
    clientID: 'client_id',
    clientSecret: 'client_secret',
    request: {
        // Set the proxy URL here!
        proxy: 'https://proxy-url.net'
    }
});
```

**Comment by divinann** [comment]
@mattwiller 

Worked like a charm!!! thank you.
