### ISSUE TITLE
Seeing a number of socket hang up requests

### ISSUE THREAD

**Issue by arjshiv** [box/box-node-sdk#139]
Hi,

I'm using the Box Node SDK as an app user for a variety of upload use cases, and I've seen a sharp increase in socket hang up issues in the last couple of days. Could you provide some guidance on how we can best solve this? 

We've been using the SDK for about 8 months now, and haven't changed anything in our underlying implementation in the last couple of weeks apart from additional error handling and logging. We're on 1.3.0 but I also don't see any changes from the PRs that refer to this issue.

Any guidance would be appreciated - thanks!

```
Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at TLSSocket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by mattwiller** [comment]
Hi @arjshiv — socket hangup errors are likely not an issue with the SDK, but with the Box API itself.  Could you give me some more details on what you're seeing?  It would helpful to know when you saw these errors start happening, if they're still continuing, and what IP address `upload.box.com` resolves to for you.

**Comment by arjshiv** [comment]
@mattwiller Thanks for the timely response. I agree, this seems like more of an API issue.

- We saw these errors start happening around two days ago. I'm still seeing them happen occasionally (3-4 times a day) 
- What's the best way to figure out the IP address that `upload.box.com` resolves to? I looked at the response object from the upload API and tried to get it from the headers/`res.connection`/`res.req.connection`, but no luck. Is there an easy way to debug this?

**Comment by mattwiller** [comment]
@arjshiv You should be able to run something like `dig upload.box.com` on your machine to get the DNS record

**Comment by arjshiv** [comment]
This is what I'm seeing using `dig` - is this helpful?

Additionally, I've seen fewer socket timeouts in the last 15-18 hours, so this may have been a one-off issue.

```
; <<>> DiG 9.8.3-P1 <<>> upload.box.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5371
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;upload.box.com.			IN	A

;; ANSWER SECTION:
upload.box.com.		44	IN	A	107.152.26.197
upload.box.com.		44	IN	A	107.152.27.197

;; Query time: 28 msec
;; SERVER: 172.17.35.1#53(172.17.35.1)
;; WHEN: Thu Jun  1 09:23:53 2017
;; MSG SIZE  rcvd: 64
```

**Comment by mattwiller** [comment]
@arjshiv There was a switchover of upload API servers in the last week or so, which may have caused some intermittent issues for you.  If the error rate is back down now, it was probably just related to that.  If the issue continues in the future, let me know, but I'm going to close this issue for now, as this doesn't seem like an SDK problem.

**Comment by arjshiv** [comment]
@mattwiller Sounds good. Thanks for shedding some light on this, and for the help!
