### ISSUE TITLE
Question: frequency of calling getTokensRefreshGrant

### ISSUE THREAD

**Issue by montrealist** [box/box-node-sdk#140]
Hi,

Is there a limit on a number of times `getTokensRefreshGrant` can be called per hour/day/etc.? We have a Grunt task that pulls files from Box, and it runs multiple times a day. Wondering if it'll ever fail due to the API refusing to provide a fresh set of tokens due to a previous request having come in too recently.

**Comment by mattwiller** [comment]
Hi @montrealist — there isn't any hard limit on token refreshes, other than our normal API rate limits.  You should only need to refresh once per hour, so I don't think it will be an issue.  Does that answer your question?

**Comment by montrealist** [comment]
Thank you - in part, yes. Where can I check the limits? Can't find them in either the reference or the docs. Also, am I correct in assuming that the rate limits apply per app?

**Comment by montrealist** [comment]
Hey @mattwiller - just following up on my last question.

**Comment by mattwiller** [comment]
Hey @montrealist, sorry for the delayed response — [this FAQ](https://community.box.com/t5/Box-Developer-Forum/FAQ-Box-Platform-and-APIs/m-p/14768#M1) has information about the rate limits.  It looks like they are per user.
