### ISSUE TITLE
Config object not deeply immutable

### ISSUE THREAD

**Issue by nickpeihl** [box/box-node-sdk#142]
The `Object.freeze` call [here](https://github.com/box/box-node-sdk/blob/master/lib/util/config.js#L155) only makes the top level properties immutable. The nested properties under `request` (for example `request.strictSSL`) are still mutable. 

I'm not sure if this is intentional or not. If not, perhaps consider using the [deep-freeze](https://www.npmjs.com/package/deep-freeze) library or the deepFreeze example listed on the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze#Examples) website.

Here's an example test that fails to throw
```
var config = new Config({
	clientID: 'id',
	clientSecret: 'secret',
});
assert.throws(function() {
        config.request.strictSSL = false;
});
```

**Comment by mattwiller** [comment]
@nickpeihl Thanks for calling this out.  If you'd like, I'm happy to accept a PR on this!  Otherwise, I'll add it to our backlog and make sure it gets taken care of.  This is somewhat low priority, so it might not be immediate, but it should be fixed before too long.
