### ISSUE TITLE
Cannot upload files from streams other than fs.createReadStream

### ISSUE THREAD

**Issue by joedski** [box/box-node-sdk#143]
I've been trying to build a server which uses Box Content to support file uploads, and I'm handling `multipart/form-data` requests using `busboy`, but when I hand off the file stream created by `busboy` to `boxClient.files.uploadFile(...)`, the latter errors out with a 500 status code.

As another data point, when I test it using a file read through `fs.createReadStream` it works fine.  However, if I pipe that stream through a PassThrough (`fs.createReadStream(...).pipe(new PassThrough())`) then it displays the above error behavior.  Creating a Readable stream which merely reads out the contents of a Buffer also fails similarly.

As an aside, I looked at `api-rquest.js` and saw this project is using `request`, which has given me erroneous behavior like above when trying to post files using streams other than those created by `fs.createReadStream`, and also erroring out when piping `fs.createReadStream` through a `PassThrough`.  Using a different library such as `got` did not have this issue in my testing.

Currently, I am getting around this by buffering files to disk, but doing even this in an efficient manner is impossible as I have to write the entire file to disk so that I can use `fs.createReadStream` to pass it off to the sdk.

I'm working on a monkeypatch of `api-request.js` as a quick test case to see if replacing `request` resolves this stream issue.  Hopefully I will be able to report back on that soon.

**Edit:** As an update, I'm going to note that efforts to make other libraries work across corporate proxies is making me consider strategies other than replacing `request`.  There're reasons `request` is so widely used, and some amount of proxy support seems to be one of them.

**Comment by joedski** [comment]
After digging Request's and FormData's codebases, I'm going to close this.  I'll leave what I found for anyone else who runs into this.

The underlying issue is this:
- Request does not have any logic to do `transfer-encoding: chunked`.
- Request always tries to set a `content-length` header.
- Request asks FormData what the length of its data is so it can send the headers before sending the body.
- FormData can only provide the length of anything which it can determine the length of.  It has provisions in its code for handling ReadStreams created by `fs.createReadStream`, HTTP `IncomingMessage`s, and `request` streams.
- Other streams must specify their known length in the `knownLength` option, passed on the object for the third parameter to `formData.append()`.
- This is impossible to do with the Box SDK (and most anything else which uses Require and thus FormData under the hood)

My workaround was to do this:
- to whatever readable stream I'm passing to the Box Client, I add these properties:
  - `myStream.httpVersion = '1.0'` (Actual value is irrelevant, but might as well use a valid one.)
  - `myStream.headers = { 'content-length': fileSizeForMyStream }`
  - `myStream.name = fileNameForMyStream`

Doing this will cause FormData to pick up on the desired metadata and report a valid size to `request`, which will thus stop truncating the body.

**Comment by u84six** [comment]
@joedski Wow, this was throwing me off for days. Thanks for digging in and figuring out the issue!

On a side note, the Request API has been recently deprecated. It will be interesting to see how all these active node libraries will recover. ;)
