### ISSUE TITLE
Cannot upload files with unspecified length/No way to specify file size in simple upload

### ISSUE THREAD

**Issue by joedski** [box/box-node-sdk#144]
So far as I can tell, when using `client.files.uploadFile()` there's no way to tell the box client the size of the file you're trying to upload.  This causes uploads to fail if you're using a stream that is _not_ one of the following:
- an `fs.ReadStream`
- an `http.IncomingMessage`
- a `request` stream

(I also suspect that if either of the `IncomingMessage` or `request` streams have the header `transfer-encoding: chunked` then uploads will similarly fail since such responses will not (should not) have the `content-length` header defined, but I have not verified this.)

In particular to my case, without some [additional finagling](https://github.com/box/box-node-sdk/issues/143#issuecomment-307539138) a file stream created by Busboy will not upload correctly when handed off to `client.files.uploadFile()` because it is a plain `Readable`, not one of the above three acceptable kinds.

For my case, passing an upload from Busboy to Box, I can (should?) probably use the chunked file uploader, but it is still surprising.  (That seems to have been either a recent addition or is just not shown in the [JSDoc site](https://rawgit.com/box/box-node-sdk/master/docs/jsdoc/Files.html) and I missed it initially.)

I can also understand not wanting to support uploads of unknown length using `transfer-encoding: chunked`, but I didn't see any comments about that in the readme or other documentation.  (I don't know if such comments truly don't exist anywhere in any Box API docs, but I don't recall seeing any.) (there is also the issue of `request` currently not having any logic to handle sending with `transfer-encoding: chunked`...)

I see there is [an old PR](https://github.com/box/box-node-sdk/pull/9) that would have added another Files method `Files.uploadFileWithOptions` which itself would have allowed the user to specify the expected size of the file stream, but it was never reviewed and is based on an old version anyway.

**Comment by mattwiller** [comment]
Hi @joedski — thanks for your detailed investigation on this!  I think you're right, this seems to be an issue with `request` and its internal handling of streams.  If possible, you should try to use the [Chunked Uploader](https://github.com/box/box-node-sdk/blob/master/docs/files.md#chunked-upload) for these types of use cases; it should be faster and more resilient to network errors.  However, it does still require you to know the size of the file beforehand; it is not currently possible to upload a file with completely unknown size.

If you can, could you confirm that switching to the Chunked Uploader solves your problem?  I think that's likely the best way forward here, since it doesn't require monkey-patching your stream and should provide additional benefits for large file uploads.

**Comment by joedski** [comment]
Thanks for pointer!  I missed the chunked uploader the first time around while getting to grips with the Box SDK, which is probably why I didn't just use that in the first place.  I'm not sure about the memory characteristics, but they'll probably be fine for our app?  I guess we'll just have to see.

I'll try to squeeze it into the backlog somewhere, maybe add it as a technical debt issue, so I might not be able to get back to it for a sprint or two.  The default chunked uploader use looks easy enough to slot into our code, though.

**Comment by stephencweiss** [comment]
@mattwiller - for what it's worth, the `Chunked Uploader` is not a panacea.

I tried refactoring to the `Chunked Uploader`, but my file is too small for it (a measly 871 bytes if I recall correctly) -- which meant I needed to use @joedski 's solution from https://github.com/box/box-node-sdk/issues/143

> My workaround was to do this:
> 
> * to whatever readable stream I'm passing to the Box Client, I add these properties:
>   
>   * `myStream.httpVersion = '1.0'` (Actual value is irrelevant, but might as well use a valid one.)
>   * `myStream.headers = { 'content-length': fileSizeForMyStream }`
>   * `myStream.name = fileNameForMyStream`

For example: 
```
fileToUpload.name = fileName;
fileToUpload.httpVersion = "1.0";
fileToUpload.headers = { "content-length": size };
await client.files
.uploadFile(FOLDER_ID, fileName, fileToUpload)
.then((file) => {
  console.log(`Successfully Uploaded`);
  uploaded = file;
})
.catch(async (err) => {
  if (err.response.body.status == 409) {
    const fileId = err.response.body.context_info.conflicts.id;
    await client.files
    .uploadNewFileVersion(fileId, fileToUpload)
    .then((file) => {
      console.log(`New Version Uploaded`);
      uploaded = file;
    })
    .catch((err) => {
      throw new Error(`New Version Error: ${err}`);
    });
  } else {
    console.log(`Generic Error ${err}`);
    throw new Error(err);
  }
});
return uploaded;
```

(This got more complicated as I wanted to upload a new version if it was already present)
