### ISSUE TITLE
The Promise support does not cover some of the BoxSDK methods

### ISSUE THREAD

**Issue by grnch** [box/box-node-sdk#145]
Promise support was added to all the BoxClients which is absolutely awesome, but it looks like some methods were missed on the BoxSDK object itself, they still require callbacks:

- getTokensAuthorizationCodeGrant()
- getTokensRefreshGrant()
- getEnterpriseAppAuthTokens()
- getAppUserTokens()
- revokeTokens()

Would you consider adding Promise support to these methods too?

**Comment by KarthikShanmugasundaram** [comment]
@grnch Sure. Thank you for sharing. We will add it out backlog.
