### ISSUE TITLE
v1.5.0 breaks client.files.uploadNewFileVersion(fileId, fileStream)

### ISSUE THREAD

**Issue by bneigher** [box/box-node-sdk#148]
Using promises.
This is throwing 
`TypeError: Can't add property error, object is not extensible.`
Any ideas?  v1.4.2 works fine and will be pinning this down as my library until further notice

**Comment by mattwiller** [comment]
@bneigher Thanks for reporting!  I'll take a look.

**Comment by mattwiller** [comment]
@bneigher I reverted the offending change and just pushed v1.5.1, which should fix the issue.  Please let me know if you're still seeing any trouble!

**Comment by bneigher** [comment]
@mattwiller thanks for the immediate turn around.  :wrench:
