### ISSUE TITLE
[question] are ids unique across all types?

### ISSUE THREAD

**Issue by yawhide** [box/box-node-sdk#156]
Sorry for posting this question here instead of support but last time I contacted them it took 2.5 months (no joke...) to answer.

My question:
Are `id` provided by the api unique across all types? (aka files/folders/web_links, etc?)

Thanks

**Comment by mattwiller** [comment]
@yawhide No, objects IDs are not unique across different types.  It is totally possible to have a folder with ID '1234' and a file with ID '1234' and a collaboration with id '1234' etc.

**Comment by yawhide** [comment]
thanks
