### ISSUE TITLE
Persistent client token refresh spin

### ISSUE THREAD

**Issue by Grahahax** [box/box-node-sdk#16]
When using a persistent client the stream spins trying to refresh tokens even if access has been revoked for the app by the user. The behaviour seems to assume all tokens can be refreshed when they expire.

The first stream error emitted looks like:
{"statusCode":401,"response":{"statusCode":401,"headers":{"server":"ATS","date":"Thu, 15 Sep 2016 15:44:11 GMT","content-length":"0","www-authenticate":"Bearer realm=\"Service\", error=\"invalid_token\", error_description=\"The access token provided is invalid.\"","vary":"Accept-Encoding","age":"0","connection":"keep-alive"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"api.box.com","port":null,"hostname":"api.box.com","hash":null,"search":"?stream_position=3942123628188338","query":"stream_position=3942123628188338","pathname":"/2.0/events","path":"/2.0/events?stream_position=3942123628188338","href":"https://api.box.com/2.0/events?stream_position=3942123628188338"},"method":"GET","headers":{"User-Agent":"Box Node.js SDK v1.0.0","Authorization":"[REMOVED BY SDK]","accept":"application/json"}}},"authExpired":true}

There doesn't appear to be a way to stop the stream and it tries to refresh once a second.

**Comment by mattwiller** [comment]
@Grahahax I can look into automatically cleaning up the stream in this case, but I'm not sure that it's always desirable.  For example, depending on how the persistent client's store is managed, a new set of tokens might become available and the stream could start flowing again.

Have you tried manually closing the stream when the error event occurs?  e.g.
```js
stream.removeAllListeners();
stream.unpipe();
stream.pause();
```

**Comment by Grahahax** [comment]
@mattwiller I had tried a few approaches and unfortunately the event stream is stuck in the refresh loop. Removing all listeners does break out of the loop, but we and up with an `Unhandled 'error' event` thrown.

It would be nice if we could update the tokens in the store but `read` is never called, only `clear` so I can't see how it would recover. Also it feels like unnecessary server load as it will continue indefinitely with the current design.

I'd suggest at least adding an option for the stream to stop after a refresh error if you don't want this to be default behaviour.

**Comment by mattwiller** [comment]
Yikes, okay.  I'll start looking into how we'd want to control the stream state in this case.

**Comment by mattwiller** [comment]
@Grahahax FYI, the latest version of the SDK (v1.2.0) includes a fix that should prevent this issue.  Please update at your earliest convenience and let me know if you're still seeing any problems!

**Comment by Grahahax** [comment]
@mattwiller Great, we'll update our version and let you know if we have any problems.

Thanks
