### ISSUE TITLE
Webhook subscription

### ISSUE THREAD

**Issue by Abiwax** [box/box-node-sdk#160]
Hi,
Is there a way to use the node sdk to subscribe to web hooks.

Thanks

**Comment by mattwiller** [comment]
Hi @Abiwax — our SDK [documentation on Webhooks](https://github.com/box/box-node-sdk/blob/master/docs/webhooks.md) is a good place to start if you want to take a look.  You can use the Node SDK to manage which webhooks you're subscribed to and to validate webhook messages when they come in.  Note that you'll still need to set up an endpoint accessible over the public Internet that the webhook messages will be sent to, as per the [Box Webhooks API docs](https://developer.box.com/reference#limitations-and-restrictions).

**Comment by Abiwax** [comment]
Thanks @mattwiller , however when i try to use the sdk for login i keep getting unauthorized auth token, what auth token is required?

**Comment by mattwiller** [comment]
@Abiwax The API uses OAuth2 tokens, which you can get via a couple different [authentication modes](https://developer.box.com/docs/authentication) depending on what kind of app you have.  If you can show me some of the code you're running, I can try and point you in the right direction.

**Comment by Abiwax** [comment]
<img width="662" alt="screen shot 2017-08-03 at 5 40 51 pm" src="https://user-images.githubusercontent.com/14370056/28942765-f00c5836-7872-11e7-80ba-5d7ebfb1d5cb.png">
@mattwiller 
Am using the instruction as stated in the image above, i think i may be using a wrong access token but theres nothing in the documentation about access tokens and how to generate one.

**Comment by mattwiller** [comment]
@Abiwax That example code is not usable as-is, you need to fill in your API credentials instead of the placeholders (i.e. `'CLIENT_ID'`, `'CLIENT_SECRET'`, and `'USER_ACCESS_TOKEN'`).  Do you already have an app set up?  If not, you may want to look over the [API documentation](https://developer.box.com/v2.0/docs/overview) for help getting started.
