### ISSUE TITLE
error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by creativesoumik** [box/box-node-sdk#164]
I got the /examples/app-auth/index.js server running and homepage displayed. But when I try to login I get this error:

An error occurred during login - error:0906D06C:PEM routines:PEM_read_bio:no start line
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line at Sign.sign (crypto.js:329:26) at Object.sign (C:\xampp\htdocs\node-home\projects\box-com\examples\app-auth\node_modules\jwa\index.js:55:45) at Object.jwsSign [as sign] (C:\xampp\htdocs\node-home\projects\box-com\examples\app-auth\node_modules\jws\lib\sign-stream.js:23:24) at Object.JWT.sign (C:\xampp\htdocs\node-home\projects\box-com\examples\app-auth\node_modules\jsonwebtoken\index.js:137:16) at TokenManager.getTokensJWTGrant (C:\xampp\htdocs\node-home\projects\box-com\examples\app-auth\node_modules\box-node-sdk\lib\token-manager.js:334:20) at AppAuthSession._refreshAppAuthAccessToken (C:\xampp\htdocs\node-home\projects\box-com\examples\app-auth\node_modules\box-node-sdk\lib\sessions\app-auth-session.js:77:20) at AppAuthSession.getAccessToken (C:\xampp\htdocs\node-home\projects\box-com\examples\app-auth\node_modules\box-node-sdk\lib\sessions\app-auth-session.js:110:8) at C:\xampp\htdocs\node-home\projects\box-com\examples\app-auth\node_modules\box-node-sdk\lib\box-client.js:216:17 at tryCatcher (C:\xampp\htdocs\node-home\projects\box-com\examples\app-auth\node_modules\bluebird\js\release\util.js:16:23) at Function.Promise.fromNode.Promise.fromCallback (C:\xampp\htdocs\node-home\projects\box-com\examples\app-auth\node_modules\bluebird\js\release\promise.js:180:30) at BoxClient._makeRequest (C:\xampp\htdocs\node-home\projects\box-com\examples\app-auth\node_modules\box-node-sdk\lib\box-client.js:213:24) at BoxClient.get (C:\xampp\htdocs\node-home\projects\box-com\examples\app-auth\node_modules\box-node-sdk\lib\box-client.js:480:14) at C:\xampp\htdocs\node-home\projects\box-com\examples\app-auth\index.js:100:17 at Layer.handle [as handle_request] (C:\xampp\htdocs\node-home\projects\box-com\examples\app-auth\node_modules\express\lib\router\layer.js:95:5) at next (C:\xampp\htdocs\node-home\projects\box-com\examples\app-auth\node_modules\express\lib\router\route.js:137:13) at Route.dispatch (C:\xampp\htdocs\node-home\projects\box-com\examples\app-auth\node_modules\express\lib\router\route.js:112:3)

**Comment by mattwiller** [comment]
Hi @creativesoumik — thanks for the detailed error report!  It looks like OpenSSL is having trouble reading your private key (which is in PEM format).  One reason for this might be the line breaks, or some other strange formatting issue.  In the Box Developer Console, you can have Box generate a key pair for you — could you try doing that and seeing if that key pair works correctly with the sample app?

**Comment by mattwiller** [comment]
Since there hasn't been any activity on this issue in over a month, I'm going to close it.  If you're still having a problem, please reopen the ticket with an update or just open a new ticket!

**Comment by shivaallani7** [comment]
> Hi @creativesoumik — thanks for the detailed error report! It looks like OpenSSL is having trouble reading your private key (which is in PEM format). One reason for this might be the line breaks, or some other strange formatting issue. In the Box Developer Console, you can have Box generate a key pair for you — could you try doing that and seeing if that key pair works correctly with the sample app?

Hi I have the same issue. I am using the key : Value pair generated in the Developer Console. is there anything I am doing incorrectly?
