### ISSUE TITLE
Incorrect error thrown when given wrong credentials.

### ISSUE THREAD

**Issue by jeffrichiefs** [box/box-node-sdk#167]
Recently began receiving the error below - the issue ended up being an incorrect `keyID`, `privateKey` and `passPhrase`. Should this error be more specific?

Stack trace:

`Trace: { Error: Expired Auth: Auth code or refresh token has expired.
at Object.buildResponseError (/usr/src/app/node_modules/box-node-sdk/lib/util/errors.js:57:23)
at Object.buildExpiredAuthError (/usr/src/app/node_modules/box-node-sdk/lib/util/errors.js:70:28)
at /usr/src/app/node_modules/box-node-sdk/lib/token-manager.js:213:21
at /usr/src/app/node_modules/box-node-sdk/lib/api-request.js:285:3
at opbeatCallbackWrapper (/usr/src/app/node_modules/opbeat/lib/instrumentation/index.js:102:27)
at wrapped (/usr/src/app/node_modules/newrelic/lib/transaction/tracer/index.js:182:28)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
 {"pid":27,"hostname":"gt9j5","name":"logger","level":20,"msg":"Errors","type":"Error","stack":"Error: Expired Auth: Auth code or refresh token has expired.\n    at Object.buildResponseError (/usr/src/app/node_modules/box-node-sdk/lib/util/errors.js:57:23)\n    at Object.buildExpiredAuthError (/usr/src/app/node_modules/box-node-sdk/lib/util/errors.js:70:28)\n    at /usr/src/app/node_modules/box-node-sdk/lib/token-manager.js:213:21\n    at /usr/src/app/node_modules/box-node-sdk/lib/api-request.js:285:3\n    at opbeatCallbackWrapper (/usr/src/app/node_modules/opbeat/lib/instrumentation/index.js:102:27)\n    at wrapped (/usr/src/app/node_modules/newrelic/lib/transaction/tracer/index.js:182:28)\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)","statusCode":400,"response":{"statusCode":400,"body":{"error":"invalid_grant","error_description":"OpenSSL unable to verify data: "},"headers":{"server":"ATS","date":"Mon, 07 Aug 2017 23:06:48 GMT","content-type":"application/json","content-length":"79","cache-control":"no-store","strict-transport-security":"max-age=31536000; includeSubDomains","vary":"Accept-Encoding","set-cookie":["box_visitor_id=5988f2888d3120.32446958; expires=Tue, 07-Aug-2018 23:06:48 GMT; Max-Age=31536000; path=/; domain=.box.com; secure","bv=OPS-41911; expires=Mon, 14-Aug-2017 23:06:48 GMT; Max-Age=604800; path=/; domain=.app.box.com; secure","cn=74; expires=Tue, 07-Aug-2018 23:06:48 GMT; Max-Age=31536000; path=/; domain=.app.box.com; secure","site_preference=desktop; path=/; domain=.box.com; secure"],"age":"0","connection":"keep-alive"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"api.box.com","port":443,"hostname":"api.box.com","hash":null,"search":null,"query":null,"pathname":"/oauth2/token","path":"/oauth2/token","href":"https://api.box.com/oauth2/token"},"method":"POST","headers":{"User-Agent":"Box Node.js SDK v1.7.0","content-type":"application/x-www-form-urlencoded","accept":"application/json","content-length":860}}},"authExpired":true,"v":1}`

**Comment by mattwiller** [comment]
Hi @jeffrichiefs!  Yes, this error message could use some updating to reflect the variety of cases where a 400 Bad Request error might happen when trying to get tokens.  Thanks for the report — I'll add it to our backlog!
