### ISSUE TITLE
issues with token exchange

### ISSUE THREAD

**Issue by dylandechant** [box/box-node-sdk#168]
I have no problem using a curl request to exchange a token (file_preview) for a certain file, I am however having issues with the sdk.

I have tried the token exchange authenticating as the app itself as well as a managed user
```javascript
const sdkClient = sdk.getAppAuthClient('enterprise', process.env.BOX_ENTERPRISE_ID);
sdkClient.asUser(process.env.BOX_APP_WORKER_ID);

box.getEmbedToken = async (fileId) => {
  try {
    await sdkClient.exchangeToken('item_preview', 'https://api.box.com/2.0/files/' + fileId);
  } catch (err) {
    console.log(err);
  }
};
```
the response i get back is this: 
```
statusCode: 400
body:
{ error: 'invalid_resource',
        error_description: 'The target resource is invalid.' } } }
```

What am I doing wrong here?

**Comment by mattwiller** [comment]
Hi @dylandechant — it looks like you're authenticating as the Service Account and then trying to generate downscoped tokens for a resource owned by a different account — is that correct?  In that case, you'll need to have a client authenticated as the app user and then do the token exchange.  As-User doesn't allow you to get a new set of tokens as that user; you can only exchange tokens that authenticate one account for tokens for the same account.

For example:
```js
const sdkClient = sdk.getAppAuthClient('user', process.env.BOX_APP_WORKER_ID);

box.getEmbedToken = async (fileId) => {
  try {
    await sdkClient.exchangeToken('item_preview', 'https://api.box.com/2.0/files/' + fileId);
  } catch (err) {
    console.log(err);
  }
};
```

Could you try that and let me know if it works for you?

**Comment by dylandechant** [comment]
@mattwiller yes, thank you, I actually figured this out shortly after I posted.  It would be helpful if this was stated somewhere in the documentation.  Consider this issue closed.

**Comment by mattwiller** [comment]
@dylandechant Great — I'm glad it's working now!  I've passed on the feedback about our documentation so that we can make it easier to know what to do here.
