### ISSUE TITLE
Inconsistency between config from developer console and node sdk

### ISSUE THREAD

**Issue by pauloliver** [box/box-node-sdk#172]
There's a small inconsistency between box's provided app settings and what the node sdk expects. 

At https://github.com/box/box-node-sdk/blob/6f9709121181b6a289e4d97907c5e54d409a8162/lib/util/config.js#L113 , the library is checking for the existence of a `keyID` field. The provided JSON from the developer console provides the following structure: 

```
{
  "boxAppSettings": {
    "clientID": "",
    "clientSecret": "",
    "appAuth": {
      "publicKeyID": "",
      "privateKey": "",
      "passphrase": ""
    }
  },
  "enterpriseID": ""
}
```

I couldn't find it noted in any documentation, but the `publicKeyID` field must be renamed to `keyID` for authorization to succeed.

**Comment by mattwiller** [comment]
Hi @pauloliver — the Node SDK provides a utility method for instantiating the SDK from the developer console JSON:

```js
var BoxSDK = require('box-node-sdk');
var sdk = BoxSDK.getPreconfiguredInstance(jsonFromDeveloperConsole);
```

This method handles mapping from the developer console information to the SDK configuration.

**Comment by pauloliver** [comment]
Thanks for the reply. Would a small PR to update documentation to include this function be ok? It's in the JSDocs, but that doesn't give it very good visibility or discoverability.

**Comment by mattwiller** [comment]
Of course!  Please feel free to submit one, or if you don't get to it in the next couple days I'll take care of it
