### ISSUE TITLE
Node SDK 1.9.0 occasionally sending upload requests with wrong order of multipart/form parts

### ISSUE THREAD

**Issue by klk-** [box/box-node-sdk#176]
Looks like this has already been addressed in https://github.com/box/box-node-sdk/pull/23 but it still happens occasionally:  13/748091 uploads with wrong format since 2017-09-01

**Comment by klk-** [comment]
The limited nature of this suggests its due to clients bypassing the code in Files.uploadFile (which sets the part order correctly), and are calling BoxClient.upload directly, passing it a formData object which has the wrong ordering.

One remediation might be to ensure/fix the ordering of parts in formData in BoxClient.upload.  Or perhaps, update documentation in BoxClient.upload and letting clients fix themselves.

**Comment by mattwiller** [comment]
This doesn't look like it's an SDK issue; the uploadFile() method does the right thing.  Users may be manually uploading with parameters in the wrong order.
