### ISSUE TITLE
Implement getReadStream for Representations

### ISSUE THREAD

**Issue by kylefernandadams** [box/box-node-sdk#180]
The current methods for fetching the representationInfo is great for checking the existence of the representations. If one does exist, there isn't a clean way to retrieve the representation content binary stream itself. Its definitely possible, but the developer experience is not ideal.

Current Experience: 
* Get Representation Info to check if there is a pdf, text, or image representation exists
* If one exists, get the content.url_template for the corresponding representation
* Trim the trailing text that contains the excess "{+asset_path}"
* Use the newly edited content url within the helper function client.get(pdf_rep_url_here)
* Get the binary content from the response body

Desired Experience:
* Get Representation Info to check if there is a pdf, text, or image representation exists
* Use a new function to get the stream of the representation client.files.getRepresentationStream('file_id', '[pdf]', callback)

**Comment by mattwiller** [comment]
We definitely already had this on the roadmap, but we appreciate the detailed proposal!  I'll update this issue when we start work on this feature.

**Comment by louis-sanna** [comment]
@kylefernandadams @mattwiller 

do you happen to have some sample code?

I can get the representation with a curl request:

`curl -X GET url  -H "authorization: Bearer accessToken" -o file.jpg`

but with client.get

```
        client.get(params.url, function (err2, res) {
            if (err2) {
                next(new Error(err));
                return;
            }
            res.pipe(fs.createWriteStream(dest));
            callback(params);
        });
```

I get a status 202 response of content/type text/html and content-length: 0.

**Comment by mattwiller** [comment]
Hey @louis-sanna — I'm not totally sure what the situation you're describing is without the actual types of URLs you're using here, but here's an example of how I got this working on my laptop just now:

```js
client.files.getRepresentationInfo(fileID, '[jpg?dimensions=1024x1024]')
	.then(representations => {

		var rep = representations.entries.find(r => r.status.state === 'success');

		if (!rep) {
			throw new Error('Representation not found');
		}

		var url = rep.content.url_template.replace('{+asset_path}', '');
		return client.get(url, { streaming: true });
	})
	.then(repStream => {
		repStream.pipe(fs.createWriteStream(dest))
			.on('close', () => console.log('Done!'));
	})
	.catch(err => console.log('Error:', err));
```

The 202 error you're seeing may indicate that the representation you requested is still being generated; you might want to handle that status code by retrying later.

**Comment by louis-sanna** [comment]
@mattwiller The representation was indeed in `pending` state, retrying later fix the error.

Thanks for the help!
