### ISSUE TITLE
How to use sdk with App Token (Server Authentication)?

### ISSUE THREAD

**Issue by ovvn** [box/box-node-sdk#188]
I got the sdk working with "OAuth 2.0 with JWT (Server Authentication)" method, e.g. when `clientId` and `clientSecret` are provided, but couldn't find a way to use the sdk properly when you have `Primary Access Token`, `Secondary Access Token` and `API Key for Your Application` with "App Token (Server Authentication)" method.

**Comment by ovvn** [comment]
Hi @mattwiller, when we get to the code `var client = sdk.getBasicClient(accessToken)` we should already have sdk initialized as follows, right?
```
var sdk = new BoxSDK({
  clientID: 'CLIENT_ID',
  clientSecret: 'CLIENT_SECRET'
});
```
But there're no `clientId` and `clientSecret` when creating an app at api.box.com with "App Token (Server Authentication)" authentication method:
![screenshot from 2017-11-29 22-41-02](https://user-images.githubusercontent.com/2973998/33395395-6bef73e4-d556-11e7-9dce-d6f6044fbb7e.png)

**Comment by mattwiller** [comment]
That's correct, but you can use dummy values for either one since the SDK will never need to use them for this auth type.  Something like this should work:

```
var sdk = new BoxSDK({
  clientID: 'DUMMY_CLIENT_ID',
  clientSecret: 'DUMMY_CLIENT_SECRET'
});

var client = sdk.getBasicClient(accessToken);
```

**Comment by ovvn** [comment]
Ok, tested as follows:
```coffeescript
    sdk = new BoxSDK
      clientID: '1'
      clientSecret: 'secret'
    
    client = sdk.getBasicClient(primaryAccessToken) # Tested with secondaryAccessToken as well
    console.log {client}
    client.users.get('me', null)
      .then (serviceAccountUser) ->
        console.log {serviceAccountUser}
      .catch (err) ->        
        console.log 'client error'
        console.log {err}
```
Getting the 403 error:
```
    { Error
     at Object.buildResponseError (/node_modules/box-node-sdk/lib/util/errors.js:57:23)
     at ret.then.response (/node_modules/box-node-sdk/lib/box-client.js:710:18)
 From previous event:
     at wrappedClientMethod (/node_modules/box-node-sdk/lib/box-client.js:698:14)
     at Users.get (/node_modules/box-node-sdk/lib/managers/users.js:57:60)
     at checkInstructions (/build/webpack:/src/server/instructions/controller.coffee:61:19)
     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:76:5)
     at next (/node_modules/express/lib/router/route.js:100:13)
     at Route.dispatch (/node_modules/express/lib/router/route.js:81:3)
     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:76:5)
     at /node_modules/express/lib/router/index.js:227:24
     at param (/node_modules/express/lib/router/index.js:324:14)
     at param (/node_modules/express/lib/router/index.js:340:14)
     at param (/node_modules/express/lib/router/index.js:340:14)
     at Function.proto.process_params (/node_modules/express/lib/router/index.js:384:3)
     at /node_modules/express/lib/router/index.js:221:12
     at Function.match_layer (/node_modules/express/lib/router/index.js:288:3)
     at next (/node_modules/express/lib/router/index.js:182:10)
     at /node_modules/express/lib/router/index.js:184:16
     at Function.match_layer (/node_modules/express/lib/router/index.js:288:3)
     at next (/node_modules/express/lib/router/index.js:182:10)
     at /node_modules/express/lib/router/index.js:184:16
      statusCode: 403,
      response: 
       IncomingMessage {
         _readableState: [Object],
         readable: false,
         domain: null,
         _events: [Object],
         _eventsCount: 4,
         _maxListeners: 100,
         socket: [Object],
         connection: [Object],
         httpVersionMajor: 1,
         httpVersionMinor: 1,
         httpVersion: '1.1',
         complete: true,
         headers: [Object],
         rawHeaders: [Array],
         trailers: {},
         rawTrailers: [],
         upgrade: false,
         url: '',
         method: null,
         statusCode: 403,
         statusMessage: 'Forbidden',
         client: [Object],
         _consuming: true,
         _dumped: false,
         req: [Object],
         request: [Object],
         toJSON: [Function: responseToJSON],
         caseless: [Object],
         read: [Function] } } }
```

**Comment by mattwiller** [comment]
This is a restriction of the auth model you're using — App Token Auth is currently only designed for content preview use cases.  See https://developer.box.com/docs/getting-started-with-new-box-view for more information, including a list of supported API endpoints.  If you want to do more than just content preview with your app, you'll need to use JWT Server Auth instead of App Token Auth.

**Comment by ovvn** [comment]
Thank you for the clarification, will use the "OAuth 2.0 with JWT (Server Authentication)" method.

**Comment by ruchitpatel56** [comment]
@ovvn : As you mentioned, you are working with 'box-node-sdk' and you succeed with OAuth 2.0 with JWT authentication.
I also want to use 'box-node-sdk' in my Angular 4 application to generate JWT token. But it is giving me error that box-node-sdk.js not found.

I am following below steps:
1. npm install --save box-node-sdk
2. Added var BoxSDK = require('box-node-sdk'); in one of the component.
But it is not finding required js file.

Can you please suggest any solution to work with Angular app?
Thanks in advance.

**Comment by mattwiller** [comment]
Hi @ruchitpatel56 — are you trying to use the Node SDK to generate the JWT token on the client side (running in a web browser)?  The Node SDK, especially the authentication functionality, is not set up to work in that context — it's designed for use on a backend Node.js server.

**Comment by ruchitpatel56** [comment]
Ok..Got it..
So in this case I have to create separate new project in node js which will work to generate JWT token only.
Thanks @mattwiller .
