### ISSUE TITLE
uploadFile does not support content_created_at or content_modified_at

### ISSUE THREAD

**Issue by neocolmartin** [box/box-node-sdk#190]
In the REST API docs, https://developer.box.com/v2.0/reference#upload-a-file documents the `content_created_at` and `content_modified_at` fields. However, there is nowhere to specify these fields in the uploadFile() function in the Box Node SDK. Indeed, there is a comment in the code stating "This method currently does not support any optional parameters such as contentModifiedAt"

For example, the uploadFile function could take an object with additional properties to be included in the request, similar to the `qs` parameter in the `files.get` function. Of course, it would still have to work if the object parameter were not provided.

**Comment by mattwiller** [comment]
Hey @neocolmartin — you're right, we'll need to add the ability to pass options to this method.  I'll look into this in the next few days!

**Comment by neocolmartin** [comment]
Thanks @mattwiller.
Is there a plan for when the next version will be pushed to npm?

**Comment by mattwiller** [comment]
We're just wrapping up another feature for inclusion in the next release — should be today or tomorrow!

**Comment by carycheng77** [comment]
Hey @neocolmartin, thanks for you patience. We just released a new version of the box-node-sdk today that supports content_created_at and content_modified_at for uploadFile and uploadNewFileVersion. 

Thanks!
