### ISSUE TITLE
How to get a thumbnail properly?

### ISSUE THREAD

**Issue by ovvn** [box/box-node-sdk#201]
Tried to load a thumbnail using sdk as follows:
```
fileId = '255515885866'
boxEnterpriseClient = sdk.getAppAuthClient 'enterprise', config.enterpriseID
boxEnterpriseClient.files.getThumbnail fileId, null, (err, response) ->
    console.log {response}
```
Got the response:
```
{ response:
    { statusCode: 302,
      location: 'https://cdn01.boxcdn.net/_assets/thumbs/27x30/application/pdf-CnKMBm.gif' } }
```
The gif file is just a picture with file format name, how can I get an actual thumbnail of uploaded file?

**Comment by mattwiller** [comment]
Hey @ovvn — the [thumbnail API documentation](https://developer.box.com/v2.0/reference#get-a-thumbnail-for-a-file) indicates that a status code of 302 means that Box could not generate a thumbnail for that file type and the provided placeholder graphic can be used instead.

**Comment by ovvn** [comment]
Hi @mattwiller, thanks for the information. Looks like `getThumbnail` doesn't work, I was able to get a thumbnail for the same file using curl endpoints as follows https://codepen.io/ovvn/pen/OzPZmx. It's interesting how to achieve the same result using sdk.

**Comment by mattwiller** [comment]
@ovvn Please be careful posting codepens like that publicly!  It has your access token in it, which if you're not careful will let someone else make API calls in your account!  *You should invalidate that access token or remove the codepen immediately!*

**Comment by mattwiller** [comment]
From looking at the codepen, I can see that it's using a different endpoint than `files.getThumbnail()` — to replicate your codepen using the SDK, call `files.getRepresentationInfo()` instead.  The representations endpoint is more general-purpose than the thumbnail one — it supports a variety of representation types and sizes, but does not return fallback placeholder graphics in the case where the thumbnail did not exist.  In your case, you got a 1024x1024 PNG, which isn't really thumbnail-sized.  If that's the size you want, you should definitely be using `files.getRepresentationInfo()`, but if you want a smaller image and a guarantee that you'll get a suitable image back even if the actual thumbnail couldn't be generated the `files.getThumbnail()` method is better-suited to that use case.

**Comment by ovvn** [comment]
@mattwiller thank you for your care, it's good that the access token invalidates automatically, i.e. expires after some time. Will use `files.getRepresentationInfo()` for now. I agree it doesn't suit very well as a thumbnail, it's rather a workaround. I wish thumbnails are available for more file formats so `files.getThumbnail()` could generate a thumbnail image for pdf, not just a placeholder.
