### ISSUE TITLE
Docs bug - explanation for authCode needed

### ISSUE THREAD

**Issue by ORESoftware** [box/box-node-sdk#209]
I am looking at this code block in the readme.md file:

```js
sdk.getTokensAuthorizationCodeGrant(authCode, null, function(err, tokenInfo) {
	// tokenInfo: {
	//  accessToken: 'ACCESS_TOKEN',
	//  refreshToken: 'REFRESH_TOKEN',
	//  acquiredAtMS: 1464129218402,
	//  accessTokenTTLMS: 3600000,
	// }
});
```

I am not sure if it's just me, but I am having trouble figuring out what the `authCode` variable represents

**Comment by mattwiller** [comment]
Hi @ORESoftware — the `authCode` variable here represents the **authorization code** from the OAuth2 flow.  See our [reference docs](https://developer.box.com/v2.0/reference/#oauth-2-overview) or [detailed OAuth2 guide](https://developer.box.com/v2.0/docs/oauth-20) for more information.
