### ISSUE TITLE
getHeaders from response?

### ISSUE THREAD

**Issue by barakbd** [box/box-node-sdk#214]
How do I read the response headers/status-code  in the node-sdk?

**Comment by mattwiller** [comment]
Hi @barakbd — can you share some of the code you're working on so I can give you more tailored help?  In general, the SDK automatically checks status codes and uses headers to create the data it passes back.  Are you seeing some sort of error?

**Comment by barakbd** [comment]
https://github.com/barakbd/box_node_sdk

**Comment by mattwiller** [comment]
@barakbd If search is returning a successful response with an empty array, are you sure that the Service Account has files matching your query in its account?  Note that the [search API documentation][search] states that content may not be indexed by search for up to 10 minutes.

As far as your original request about request headers and status code, can you point me to a specific place in your code where you'd like to have that information or where you're seeing an error?

[search]: https://developer.box.com/v2.0/reference/#searching-for-content

**Comment by barakbd** [comment]
I found the problem I was creating content through the website logged in as the user that owns the service account.
User !== Service Account :)

Thanks for the prompt replies!

I found this - https://community.box.com/t5/Box-Developer-Forum/Service-account-can-only-quot-see-quot-content-it-owns/td-p/30004

**Comment by mattwiller** [comment]
Ahh, yeah — that's a common misconception, glad you got the information you needed!  The account of the developer who created the application is not the same as the service account, and both are different from any app user accounts created by the application.  Each account has its own user ID and content, though you can [collaborate content][collab] between them to share it among different accounts!

[collab]: https://github.com/box/box-node-sdk/blob/master/docs/collaborations.md#add-a-collaboration

**Comment by barakbd** [comment]
I see.
Can a user invite a Service Account as collaborator the same was as any other user, i.e. through the website UI and not API?

**Comment by mattwiller** [comment]
I don't know of a good way to do that through the UI — I believe you need to get a token for the developer user and collaborate the service account via the API.

**Comment by barakbd** [comment]
Thought so :(

Thanks!
