### ISSUE TITLE
Error on client.search.query

### ISSUE THREAD

**Issue by barakbd** [box/box-node-sdk#219]
This is my snippet of code:

``` javascript  

   boxManagedUserClient.search.query(req.params.folderName/* {
                fields: 'name,modified_at,size,extension,permissions,sync_state, collections',
                type: "folder",
                limit: 2,
                offset: 0,
            } */).then(foldersArray => {

```

And below is the error response I get.
When I try the token in a direct API request (Bearer in the header), the request succeeds.

```json
{
"error": {
"statusCode": 401,
"response": {
"statusCode": 401,
"headers": {
"date": "Wed, 31 Jan 2018 01:48:16 GMT",
"content-length": "0",
"strict-transport-security": "max-age=31536000; includeSubDomains",
"www-authenticate": "Bearer realm=\"Service\", error=\"invalid_token\", error_description=\"The access token provided is invalid.\"",
"vary": "Accept-Encoding",
"age": "0",
"connection": "keep-alive"
},
"request": {
"uri": {
"protocol": "https:",
"slashes": true,
"auth": null,
"host": "api.box.com",
"port": null,
"hostname": "api.box.com",
"hash": null,
"search": "?query=Pseud",
"query": "query=Pseud",
"pathname": "/2.0/search",
"path": "/2.0/search?query=Pseud",
"href": "https://api.box.com/2.0/search?query=Pseud"
},
"method": "GET",
"headers": {
"User-Agent": "Box Node.js SDK v1.11.0 (Node v6.12.3)",
"Authorization": "[REMOVED BY SDK]",
"accept": "application/json"
}
}
}
}
}
```

**Comment by mattwiller** [comment]
Hi @barakbd — this looks like an auth issue; could you show me how you're generating the `boxManagedUserClient` that you're using?  Also, what steps did you take to make it work manually?

**Comment by barakbd** [comment]
Goal: I am trying to search for a folder named ""Pseudo" which is owned by user testuser@domain.com, using OAuth.

Leg 1 - user logs into box and authorizes my app following this link: https://account.box.com/api/oauth2/authorize?response_type=code&client_id=CLIENT_ID&box_login=testuser@domain.com&redirect_uri=http://localhost:3200/box/linkCardFolder/**Pseud**

Legs 2 and 3 - my server is listening on this path: "/box/linkCardFolder/:folderName", retrives CODE, gets AccessToken, and creates a boxManagedUserClient  for getting the folder_id by querying folder name (partial folder name should work, according to ths docs and also when I test it with a direct API call - see below)
Controller for this path is:

```javascript 
const boxSDK = require('box-node-sdk');
const fs = require('fs');
// Read and parse the automatically created Box configuration file.
let configFile = fs.readFileSync('box_config_managed_user.json');
configFile = JSON.parse(configFile);
// Initialize the SDK with the Box configuration file 
let boxManagedUserSDK = boxSDK.getPreconfiguredInstance(configFile);
boxManagedUserSDK.getTokensAuthorizationCodeGrant(req.query.code, null).then(AccessToken => {
            //create a client using the AccessToken
            const boxManagedUserClient = managedUserSDK.getBasicClient(**AccessToken**);
            //Search for folder id by folder name from req.params
            boxManagedUserClient.search.query(req.params.folderName/* {
                fields: 'name,modified_at,size,extension,permissions,sync_state, collections',
                type: "folder",
                limit: 2,
                offset: 0,
            } */).then(foldersArray => {
                if (foldersArray.length === 0) {
                    res.status(404)
                    res.set('Content-Type', 'application/json');
                    res.json({
                        error: "Item not found"
                    })
                } else if (foldersArray.length > 1) {
                    res.status(300)
                    res.set('Content-Type', 'application/json');
                    res.json(foldersArray)
                } else {
                    boxManagedUserClient.collaborations.createWithUserID(
                        'SERVICE_ACCOUNT_USER_ID',
                        foldersArray[0].id,
                        boxManagedUserClient.collaborationRoles.EDITOR, {
                            type: boxManagedUserClient.itemTypes.FOLDER
                        }).then(collaborationID => {
                        res.json(collaborationID)
                    })
                }
            }).catch(folderArrayError => {
                res.send({
                    folderName: req.params.folderName,
                    error: folderArrayError
                })
            }) // end returned foldersArray
        }) //end getTokensAuthorizationCodeGrant
```

Manual search for folder id by folder name works: (using returned **AccessToken** with TTL > 1 hour )

```curl
GET /2.0/search?query=Pseu&amp;type=folder&amp;ancestor_folder_ids=0 HTTP/1.1
Host: api.box.com
Authorization: Bearer <**ACCESS_TOKEN_RETRIEVED_BY_OAUTH**>
Cache-Control: no-cache
Postman-Token: <POSTMAN_TOKEN>
```

I have a feeling it is related to scopes, which I would need my enterprise admin to authorize before deploying.

**Comment by mattwiller** [comment]
Two things I noticed looking at your code above:

1. `BoxManagedUserSDK.getTokensAuthorizationCodeGrant(req.query.code, null)` returns `Promise<TokenInfo>` (a promise resolving to the full token info object), so in `.then()` you don't get the access token, you get an object with the access token in it.  You'll need to take the access token from that object and put it into the client.

2. We have a [Persistent Client](https://github.com/box/box-node-sdk/blob/master/docs/authentication.md#oauth2-authentication) that's made for use with traditional 3-legged OAuth2 that will automatically store and refresh the tokens for you.  You may want to consider using it to prevent needing to manually handle token refresh.

Can you try changing your code to handle the TokenInfo correctly and see if that fixes your issue?

**Comment by barakbd** [comment]
Thanks! Stupid mistake by me :)

Is there a @types/box-node-sdk npm package?
I am looking to start using Typescript.

**Comment by barakbd** [comment]
Now getting this error - "message": "External collaboration is restricted on this item",
Scopes?

**Comment by mattwiller** [comment]
@barakbd We don't currently provide Typescript definitions, but they're something we might look to add in the future.  It's good data for us to know that people are interested in them!

The "External collaboration is restricted on this item" error message you're seeing usually means that the enterprise administrator or item owner has disallowed collaborating that item with users outside of their enterprise.  This isn't related to scopes, but to the permissions and settings on the item.

**Comment by barakbd** [comment]
Can Service Account invite external collaborators?
If the Service Account is an Owner of a folder can it invite external collaborators?
Is there a setting to limit that?

**Comment by mattwiller** [comment]
My understanding is that if External Collaboration is restricted, no account can add external collaborators to that item.  This setting would apply in cases where the content in that folder or in the entire enterprise is considered too sensitive to share outside the enterprise.  In this case, the only people you can add as collaborators are people inside the enterprise (managed users).

**Comment by barakbd** [comment]
Thanks.
After we receive the code, our backend runs some functions.
On success we need to refresh our frontend.

However, since this is OAuth, and the request to our redirect URI is made from a box endpoint
, our frontend has no way of getting a response.
What is the best way to handle this?

Is there a way to get the code in the frontend and with a hook?

**Comment by mattwiller** [comment]
Unfortunately, there is no way to get the auth code in a client-side application.  You will need a backend server to receive the auth code and exchange it for a token pair.  Without knowing much about exactly how your application is structured, I can't really make a lot of recommendations about how best to structure everything.  However, in general, I would say that anything on the client should not handle authentication at all — your backend should manage tokens and pass an appropriately-scoped access token down to the client as needed.

**Comment by barakbd** [comment]
Thought so.

How can I generate a developer token for the service account?
When I go to the app and generate a developer token, then call /users/me, it retrieves the user who created the app, not the app service account.

**Comment by barakbd** [comment]
Perfect!

Thank you very much for all the help!
Issue Closed :)
