### ISSUE TITLE
Empty entries array on doing enterprise search

### ISSUE THREAD

**Issue by Arvind6353** [box/box-node-sdk#221]
Hi , 
On doing a search using service account client with scope set as enterprise_content , getting the below response . 

**https://api.box.com/2.0/search?query=sales&file_extensions=pdf,docx&scope=enterprise_content**

How do I get the entries array?

Below is the response am getting :
{
    "total_count": 253521,
    "entries": [],
    "limit": 30,
    "offset": 0
}

**Comment by carycheng** [comment]
Hey @Arvind6353, 

Thank you for reaching out - couple of questions

1. Wondering if you are using an user account or a service account to make the callout to the search endpoint? Ideally you should be using the service account to perform this action as it represents a Box Platform application and the access token generated from a service account has access to content across your enterprise whereas a token generated from an app user only has access to content inside their own account.

The [FAQ](https://developer.box.com/docs/service-account) section is great if you had other questions regarding functionality and limitations of the service account.

2. If possible, could you check the scoping of the application you have made? The "Read and Write all files stored in Box" scope should be checked. If it was not enabled before - after checking that checkbox you will have to go to your enterprise settings page -> Apps tab -> Reauthorize your application in order for the scoping to come into effect. 

Let us know if that solved your problem, thank you!

**Comment by Arvind6353** [comment]
Hi @carycheng .

I am using the service account to make the search api call .  I checked the scope settings and 
"Read and Write all files stored in Box" scope is already checked. When I do a search using the service account client am getting the below response.

**{
    "total_count": 417046,
    "entries": [],
    "limit": 30,
    "offset": 0
}**


I wonder why the entries array is coming as empty though the total is showing a huge no .

Is there a way i can get the entries .

AM using the following method from box-node-sdk to search

var box = require('box-node-sdk');
var session = box.getPreconfiguredInstance(configFile);
var serviceAccountClient = session.getAppAuthClient('enterprise','MY ENTERPRISE ID');
serviceAccountClient .search.query( 
        'Test',
        {
          file_extensions: 'doc,docx,pptx',
          limit: 20,
          offset: 0,
        },
        function(err, res){
          if(err){
            console.log("errrrrr -",err);
            return;
          }
          console.log(res);
     
        }
      );

**Comment by mattwiller** [comment]
@Arvind6353 The discrepancy between `total_count` and the contents of the array can occur when our search index returns items that are filtered out of the final result set, for example because they have been deleted or the user does not have permission to view those files anymore.  If the first 30 items returned from the search index were all filtered out for the final result set, you'll get an empty array back.

When you see results like this, you can do two things: raise the value or the `limit` parameter to hopefully get some results back, and continue paging into the search results using the `offset` parameter.  Eventually you should get to the results that your application can view.  In general, the API cannot guarantee that the `entries` array will contain exactly `limit` values, so you should use paging to continue forward in the search results until you reach the expected number of results or `total_count`.

If you increase the `limit` or page forward, do you see some results?

**Comment by Arvind6353** [comment]
Hi @mattwiller , thanks for the explanation .
Looks like those docs do not have the permission .

I created a folder with some docs in my box and used service account to access the content via search api and it is returning the result after adding the app as a collaborator to the folder

I will try to get some permission for docs outside of my account and try this step out and will get back if I find issues .

Thanks again :)

**Comment by Arvind6353** [comment]
Hi @mattwiller , 

I am able to integrate with Box node sdk and using service account and am able to get the results.

In some of the results , I find that the **shared_link** is coming as null . What could be the reason ?

When I go that **document and click on share link** ( it is generating a shared link). And later when I fire the same search call , I am able to see the shared link for that document .


Is there a way to get the link to the docs by default with out doing the above ?

**Comment by mattwiller** [comment]
The `shared_link` field is not populated by default; you have to specifically choose to generate a shared link for each item.  This is done for security reasons — not every file should be shared publicly!  In this case, your service account seems to have the correct permissions to view the shared link, those items just don't have a shared link yet.  You can [create a shared link using the SDK](https://github.com/box/box-node-sdk/blob/master/docs/files.md#create-a-shared-link):

```js
// Pick the access level that you want, e.g. OPEN or COLLABORATORS or COMPANY
// Using DEFAULT will pick whatever the enterprise settings have as the default
var sharedLinkAccessLevel = client.accessLevels.DEFAULT;
client.files.update('FILE_ID', { shared_link: sharedLinkAccessLevel }, function(err, file) {
    if (err) {
        // handle error case
    }

    var sharedLink = file.shared_link.url;
});
```

**Comment by Arvind6353** [comment]
Thanks for the detailed explanation :)
