### ISSUE TITLE
multiple files upload

### ISSUE THREAD

**Issue by praveen4554** [box/box-node-sdk#224]
Hi 

i would like to upload multiple files to box at a time is der any function for multiple files upload in box-node-sdk 

Thanks,
Praveen

**Comment by carycheng** [comment]
Hey @praveen4554, 

Unfortunately we don't have a method for the user to upload multiple files at once. Can I dig in more for your use case? Maybe there is something else that might be helpful I can assist with. 

Thanks!

**Comment by praveen4554** [comment]
Hi @carycheng 

   From UI user uploaded 3 to 5 files and submit the files. so we are getting those files and I need to upload them into BOX at a time can you help me for this

Thanks,
Praveen

**Comment by carycheng** [comment]
Hey @praveen4554, 

If you are building a application with ui/functionality where you allow users to upload multiple files to Box you should try out out our Box Content Uploader seen [here](https://developer.box.com/docs/box-content-uploader)

The set up is pretty straightforward and allows the user to drag and drop multiple items and upload to a Box folder you specify(through the folder id). This also allows you to quickly incorporate an uploader into the application you are building with minimal code. 

You can try this out for yourself really quick with the codepen found [here](https://codepen.io/box-platform/pen/QvqGwr). Just follow steps found in the right most column and you should be up and running ~10 minutes. 

Let me know if this is something you were looking for, thanks!

**Comment by praveen4554** [comment]
Hi @carycheng 

   I know this method 

Thanks
Praveen

**Comment by praveen4554** [comment]
Hi @carycheng 

     I would like to read the file in streams and convert the file data to base64 can you please guide me the method name for reading the file with fileID

Thanks,
Praveen

**Comment by carycheng** [comment]
Hey @praveen4554, this should accomplish what you are trying to do: 

https://github.com/box/box-node-sdk/blob/master/docs/files.md#download-a-file

**Comment by praveen4554** [comment]
Hi @carycheng, it returns path, href,pathname I want to convert to the stream to base64 I didn't get anything related data in the stream
my response
    "pathname": "/d/1/WYzpf8CF3EeFrUEkmlFLdTv83PTUTVzpO45FhS1PCdPkUTGrIvy9c8mWuothWhQ9KsQrPCi_Vt2ygj_lYDkm9KPMcak-eh6AbiE-lmdSV4DXyJyvqm12T5gFyQN-9X4lf_bwryxKsnBmjwJlLO-zEEk0wmdy3O2U2y3Trfg2zafxXGXWLe89WUNWnWK8LpoG5LKZybCmDHJ8ns8jUSX3pwIrHZq8lpupBjYbi3V-ajfQpXsClUsLRotXIhzu89QqNSw3a8i7KYAF0Wzm6hXHm3qIgnqE9Ut69EggP5B9D02i6cPkAFk2gEck9ZVFQV_tgZwcTGUd-Bit3q8t6AHXSuuMn_UkHKJqFVhMZFwpOoKUURayUWDubghYADDLmWnaezgSiihR8MCA6aiPhwB65gdY2KF8WPrmIZq3oSEv6L78TBp3P-kQcCwVTn8qLT8dh8sOEnqgKH0wX7SfYCJyTY_-RPJEYRhTvRCta50R-j-Enwz6FUHHGih9YZYXArulP2ncM7NU0Wa0yHjtGNSHykl2okF86a9s8D9OopxIdTYNXJPscgquidtJd0FZudJLdBoenD7weEPtl6culpzgl58xqzmx5AAhEXLAHnqUwvWXAFFwhl8GTYIo35OWWs-T3-PfJo1nwlLQDJeQNcCFxjpqGBiz1U9bvI7ksThOyZvTnSV1zuK0mIkjqHWKY452enAKGHrEcBghjfoNwjKfod0y6Irb3EPFF4p3J0bzjlUGI-7ociMeZewg1aZTPuRMILmI5iPtU37SF7y8aM3qGd37Fu0MWUfYTWjnb_cKGHEvwl4ggHbXfJ7b_J0kvD-dm3U6GUAVdrmK8zbFgXDzNObRmkrgA3aFWFI3mh0jZN4fKm2RqcRtsnyw_YZzlVhnaui59XK91XKR6sTm0ahPVVF7t-YlDJ9qmVWuQN_LR3IfKBpaXIg-GNrOrSGJdrvwSSAUUQxnX4c4R0n2RJjBdpI8LN6qUqWcEZ8woajtKzWwBbtZkLcMcCVL5WG-F1NpZ1DxPREAv3rNizKjIfzU3bAEGNMO3mR4KmOjq_Kp5exzSmKfOQwJJa2BtS59Ayt9XLmO3o_uySJ35uJjpfuJYfjCrKsfy9Gq8yoyQXzeO4yTEne2FMOAvg6UBlzzFgp4djDBXamgjgr2yc76w7GlROnIGGMhTVcBeMjyIMrXVSOWuKEPmpKMslanGtug8DANfenHcUekwZK5I-SCgpi55j5enAniccR47N0nfnw4gpDp40BseOopDGhnXA../download",
            "path": "/d/1/WYzpf8CF3EeFrUEkmlFLdTv83PTUTVzpO45FhS1PCdPkUTGrIvy9c8mWuothWhQ9KsQrPCi_Vt2ygj_lYDkm9KPMcak-eh6AbiE-lmdSV4DXyJyvqm12T5gFyQN-9X4lf_bwryxKsnBmjwJlLO-zEEk0wmdy3O2U2y3Trfg2zafxXGXWLe89WUNWnWK8LpoG5LKZybCmDHJ8ns8jUSX3pwIrHZq8lpupBjYbi3V-ajfQpXsClUsLRotXIhzu89QqNSw3a8i7KYAF0Wzm6hXHm3qIgnqE9Ut69EggP5B9D02i6cPkAFk2gEck9ZVFQV_tgZwcTGUd-Bit3q8t6AHXSuuMn_UkHKJqFVhMZFwpOoKUURayUWDubghYADDLmWnaezgSiihR8MCA6aiPhwB65gdY2KF8WPrmIZq3oSEv6L78TBp3P-kQcCwVTn8qLT8dh8sOEnqgKH0wX7SfYCJyTY_-RPJEYRhTvRCta50R-j-Enwz6FUHHGih9YZYXArulP2ncM7NU0Wa0yHjtGNSHykl2okF86a9s8D9OopxIdTYNXJPscgquidtJd0FZudJLdBoenD7weEPtl6culpzgl58xqzmx5AAhEXLAHnqUwvWXAFFwhl8GTYIo35OWWs-T3-PfJo1nwlLQDJeQNcCFxjpqGBiz1U9bvI7ksThOyZvTnSV1zuK0mIkjqHWKY452enAKGHrEcBghjfoNwjKfod0y6Irb3EPFF4p3J0bzjlUGI-7ociMeZewg1aZTPuRMILmI5iPtU37SF7y8aM3qGd37Fu0MWUfYTWjnb_cKGHEvwl4ggHbXfJ7b_J0kvD-dm3U6GUAVdrmK8zbFgXDzNObRmkrgA3aFWFI3mh0jZN4fKm2RqcRtsnyw_YZzlVhnaui59XK91XKR6sTm0ahPVVF7t-YlDJ9qmVWuQN_LR3IfKBpaXIg-GNrOrSGJdrvwSSAUUQxnX4c4R0n2RJjBdpI8LN6qUqWcEZ8woajtKzWwBbtZkLcMcCVL5WG-F1NpZ1DxPREAv3rNizKjIfzU3bAEGNMO3mR4KmOjq_Kp5exzSmKfOQwJJa2BtS59Ayt9XLmO3o_uySJ35uJjpfuJYfjCrKsfy9Gq8yoyQXzeO4yTEne2FMOAvg6UBlzzFgp4djDBXamgjgr2yc76w7GlROnIGGMhTVcBeMjyIMrXVSOWuKEPmpKMslanGtug8DANfenHcUekwZK5I-SCgpi55j5enAniccR47N0nfnw4gpDp40BseOopDGhnXA../download",
            "href": "https://public.boxcloud.com/d/1/WYzpf8CF3EeFrUEkmlFLdTv83PTUTVzpO45FhS1PCdPkUTGrIvy9c8mWuothWhQ9KsQrPCi_Vt2ygj_lYDkm9KPMcak-eh6AbiE-lmdSV4DXyJyvqm12T5gFyQN-9X4lf_bwryxKsnBmjwJlLO-zEEk0wmdy3O2U2y3Trfg2zafxXGXWLe89WUNWnWK8LpoG5LKZybCmDHJ8ns8jUSX3pwIrHZq8lpupBjYbi3V-ajfQpXsClUsLRotXIhzu89QqNSw3a8i7KYAF0Wzm6hXHm3qIgnqE9Ut69EggP5B9D02i6cPkAFk2gEck9ZVFQV_tgZwcTGUd-Bit3q8t6AHXSuuMn_UkHKJqFVhMZFwpOoKUURayUWDubghYADDLmWnaezgSiihR8MCA6aiPhwB65gdY2KF8WPrmIZq3oSEv6L78TBp3P-kQcCwVTn8qLT8dh8sOEnqgKH0wX7SfYCJyTY_-RPJEYRhTvRCta50R-j-Enwz6FUHHGih9YZYXArulP2ncM7NU0Wa0yHjtGNSHykl2okF86a9s8D9OopxIdTYNXJPscgquidtJd0FZudJLdBoenD7weEPtl6culpzgl58xqzmx5AAhEXLAHnqUwvWXAFFwhl8GTYIo35OWWs-T3-PfJo1nwlLQDJeQNcCFxjpqGBiz1U9bvI7ksThOyZvTnSV1zuK0mIkjqHWKY452enAKGHrEcBghjfoNwjKfod0y6Irb3EPFF4p3J0bzjlUGI-7ociMeZewg1aZTPuRMILmI5iPtU37SF7y8aM3qGd37Fu0MWUfYTWjnb_cKGHEvwl4ggHbXfJ7b_J0kvD-dm3U6GUAVdrmK8zbFgXDzNObRmkrgA3aFWFI3mh0jZN4fKm2RqcRtsnyw_YZzlVhnaui59XK91XKR6sTm0ahPVVF7t-YlDJ9qmVWuQN_LR3IfKBpaXIg-GNrOrSGJdrvwSSAUUQxnX4c4R0n2RJjBdpI8LN6qUqWcEZ8woajtKzWwBbtZkLcMcCVL5WG-F1NpZ1DxPREAv3rNizKjIfzU3bAEGNMO3mR4KmOjq_Kp5exzSmKfOQwJJa2BtS59Ayt9XLmO3o_uySJ35uJjpfuJYfjCrKsfy9Gq8yoyQXzeO4yTEne2FMOAvg6UBlzzFgp4djDBXamgjgr2yc76w7GlROnIGGMhTVcBeMjyIMrXVSOWuKEPmpKMslanGtug8DANfenHcUekwZK5I-SCgpi55j5enAniccR47N0nfnw4gpDp40BseOopDGhnXA../download"
        },

**Comment by mattwiller** [comment]
Hi @praveen4554 — the `getReadStream()` method returns a [Readable stream](https://nodejs.org/api/stream.html#stream_class_stream_readable) — you'll need to either read the data from the stream using `stream.on('data')` or something similar and encode it yourself, or implement some sort of [Transform stream](https://nodejs.org/api/stream.html#stream_class_stream_transform) to encode the data yourself before sending the data to the client.  The `pathname` and `href` properties you pasted above are internal properties of the stream, and not intended for use.
