### ISSUE TITLE
Stupid question - is there a front-end JS SDK for box

### ISSUE THREAD

**Issue by ORESoftware** [box/box-node-sdk#225]
Stupid question - is there a front-end JS SDK for box?

sorry just on a constraint here

**Comment by ORESoftware** [comment]
I see this: 
https://github.com/allenmichael/box-javascript-sdk

is that the best one?

**Comment by mattwiller** [comment]
@ORESoftware For now, that is the best one to use.  It's on our roadmap to eventually combine the two SDKs and provide an isomorphic SDK that works on both Node.js and browsers, but that is not yet available.

**Comment by ORESoftware** [comment]
thanks for the feedback! sounds good
