### ISSUE TITLE
"clientID" must be set via init() before using the SDK

### ISSUE THREAD

**Issue by sagardew** [box/box-node-sdk#238]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I am passing string values of clientID and clientSecret key coming from the config file , still i face this error.

**Comment by mattwiller** [comment]
@sagardew Unfortunately, the stack trace you provided doesn't include any SDK stack frames, so it's not very helpful for me.  Could you show me how you're instantiating the SDK?  That error message isn't very helpful — I'll take an action item to fix it — but what it's telling you is that the SDK needs to be instantiated with a client ID and client secret like the following:

```js
var sdk = new BoxSDK({
    clientID: 'YOUR_CLIENT_ID',
    clientSecret: 'YOUR_CLIENT_SECRET'
});
```

Alternatively, if you have the JSON config file from the Box Developer Console, you can use that directly:

```js
var config = require('/path/to/config.json');
var sdk = BoxSDK.getPreconfiguredInstance(config);
```

**Comment by sagardew** [comment]
Hi @mattwiller  , Thanks for the quick reply . i am putting the stack frames from sdk . and i am instantiating in the contructor of my .ts file. 

AssertionError: "clientID" must be set via init() before using the SDK.
at validateBasicParams (/Users/sagardew/boxi/node_modules/box-node-sdk/lib/util/config.js:97:2)
at new Config (/Users/sagardew/box/node_modules/box-node-sdk/lib/util/config.js:137:2)

I have seen a similar issue addressed in the issues but i am sending a clientID and clientSecret as a string, even if i hadrcode the strings it doesnt work.

this.sdk = new BoxSDK({
            clientId: settings.clientId,
            clientSecret: settings.clientSecret,
            redirectUri: settings.redirectUrl,
            accessToken: settings.accessToken,
            logLevel: settings.debug ? 'DEBUG' : undefined
        });

**Comment by mattwiller** [comment]
@sagardew I see your problem — your code uses `clientId` (with lower case 'd'), but the expected key is `clientID` (with upper case 'D').  Also, I'm curious — what are you using the `redirectUri`, `accessToken`, and `logLevel` options for?  Those aren't options that the SDK takes in its constructor.

**Comment by sagardew** [comment]
Thanks @mattwiller for your quick response , It was a silly mistake by my end. Also redirecturi and accesstoken was just a proto created , they are not in use.
