### ISSUE TITLE
How to stream files to Box using multiparty

### ISSUE THREAD

**Issue by barakbd** [box/box-node-sdk#241]
- [x ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Cannot figure out how to stream a file to Box from an incoming POST API call.

### Versions Used
Node SDK: ^1.12.1  
Node.js: v9.4.0

### Steps to Reproduce
``` typescript
// https://github.com/box/box-node-sdk/blob/master/docs/files.md#upload-a-file
// http://qnimate.com/stream-file-uploads-to-storage-server-in-node-js/

import {
  Router,
  Request,
  Response
  // NextFunction,
  // RequestHandler
} from "express";

import * as multiparty from "multiparty";

const createRoutes: Function = (boxClient: any): Router => {
  const router: Router = Router();

  const fileMethods = new FileMethods(boxClient);
  router.post("/:parent_folder_id", fileMethods.create);
  router.get("/:id", fileMethods.get);
  return router;
};

export default createRoutes;

class FileMethods {
  private _boxClientLocal: any;

  constructor(boxClient: any) {
    this._boxClientLocal = boxClient;
  } //end constructor

  public create = (req: Request, res: Response) => {
    const multipartyForm: multiparty.Form = new multiparty.Form();
    multipartyForm.on("part", (part: multiparty.Part) => {
      if (part.filename) {
        // const fileSize = Number(req.get("content-length"));
        /*         
        this._boxClientLocal.files
          .uploadFile(req.params.parent_folder_id, part.filename, part)
          .then((file: any) => {
            return res.status(200).json(file);
          })
          .catch((err: any) => {
            return res.status(err.statusCode).json(err);
          });
        */

        this._boxClientLocal.files
          .getChunkedUploader(
            req.params.parent_folder_id,
            Number(req.get("content-length")),
            part.filename,
            part
          )
          .then((file: any) => {
            return res.status(200).json(file);
          })
          .catch((err: any) => {
            return res.status(err.statusCode).json(err);
          });
      }
    });
    multipartyForm.on("error", error => {
      res.json(error);
    });
    //start parsing
    multipartyForm.parse(req);
  }; //end create

  public get = (req: Request, res: Response) => {
    this._boxClientLocal.files
      .get(req.params.id)
      .then((fileInfo: any) => {
        return res.status(200).json(fileInfo);
      })
      .catch((err: any) => {
        return res.status(err.statusCode).json(err);
      });
  }; //end get
} //end class FileMethods

```
### Error Message, Including Stack Trace
Sending file from Postman using form-data, no headers set (Postman sets them automatically, and I can see they are correct)

If I try using the getChunkedUploader method, I get error:

>"message": "File size 495097 less than minimum allowed for this API: 20000000",

If I try using "uploadFile" method, I simply get error:

>"statusCode": 400,

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
Hey @barakbd — per the [Chunked Upload API documentation](https://developer.box.com/v2.0/reference/#chunked-upload), the minimum file size allowed is 20 MB.  The error message you're getting indicates that the file you're trying to upload is ~500 KB, way too small to use this API for.  You should use the [standard upload method](https://github.com/box/box-node-sdk/blob/master/docs/files.md#upload-a-file) instead for files that small.

**Comment by barakbd** [comment]
I tried the standard upload method and I just get: "statusCode": 400.
Please see above the commented out code

``` Typescript
        /*   
        this._boxClientLocal.files
          .uploadFile(req.params.parent_folder_id, part.filename, part)
          .then((file: any) => {
            return res.status(200).json(file);
          })
          .catch((err: any) => {
            return res.status(err.statusCode).json(err);
          });
        */
```

**Comment by mattwiller** [comment]
Can you share more detail about the error you're seeing with standard upload?  There are multiple reasons why you might get a 400 error; without knowing more I can't really troubleshoot this issue.

**Comment by barakbd** [comment]
Sure. BTW, when I use "preflightUploadFile" I get success:
```
{
    "upload_url": "https://upload.box.com/api/2.0/files/content?upload_session_id=AADDD593CDE847EEBEA9C949CE55E454",
    "upload_token": null
}
```

Here is the full error:

```
{
    "statusCode": 400,
    "response": {
        "statusCode": 400,
        "headers": {
            "date": "Tue, 13 Mar 2018 19:29:48 GMT",
            "content-type": "text/html; charset=UTF-8",
            "content-length": "0",
            "age": "0",
            "strict-transport-security": "max-age=31536000",
            "connection": "keep-alive"
        },
        "request": {
            "uri": {
                "protocol": "https:",
                "slashes": true,
                "auth": null,
                "host": "upload.box.com",
                "port": 443,
                "hostname": "upload.box.com",
                "hash": null,
                "search": null,
                "query": null,
                "pathname": "/api/2.0/files/content",
                "path": "/api/2.0/files/content",
                "href": "https://upload.box.com/api/2.0/files/content"
            },
            "method": "POST",
            "headers": {
                "User-Agent": "Box Node.js SDK v1.12.1 (Node v9.4.0)",
                "Authorization": "[REMOVED BY SDK]",
                "X-Box-UA": "agent=box-node-sdk/1.12.1; env=Node/9.4.0",
                "accept": "application/json",
                "content-type": "multipart/form-data; boundary=--------------------------489402530773022448013638",
                "content-length": 407
            }
        }
    }
}
```

**Comment by barakbd** [comment]
Reading Multiprty's docs (https://www.npmjs.com/package/multiparty) , I can see that:

> 'part' (part)
> 
> Emitted when a part is encountered in the request. part is a **ReadableStream**. It also has the following properties:

and on the box -node-sdk docs:

> The simplest way to upload a file to a folder is by calling the files.uploadFile(parentFolderID, filename, content, callback) method with a **stream.Readable** or Buffer of the file to upload.

I just wonder if the issue could be that I am not creating a continuous stream from all the incoming "parts" read by "multiparty.Form"

**Comment by mattwiller** [comment]
@barakbd Internally, the `request` library that we use (actually its `form-data` dependency) [requires that any streams it uses have information about how large the file is](https://github.com/form-data/form-data/blob/master/lib/form_data.js#L114) (in order to set the Content-Length header on the request).  This is true for streams from `fs.createReadStream()`, for example, but I'm not sure if `multiparty` streams work the same way.  They may not be compatible with `request`; you might have to ensure the stream has sufficient information on its length.  If the file you're uploading is guaranteed to be small, you may want to consider just reading the stream into a Buffer and uploading that instead.

**Comment by barakbd** [comment]
That's what I thought.
Where can I set content-length so the request knows there is more data coming?

**Comment by barakbd** [comment]
I think this is related to this issue: https://github.com/box/box-node-sdk/issues/143

**Comment by barakbd** [comment]
Solved. Using Multer. Will post code sample soon.

**Comment by barakbd** [comment]
Is it possible to create shared link when uploading a file, maybe by passing an option?
Does it have to be done as a separate API call to "update"?

**Comment by barakbd** [comment]
Also, is it possible to set unsharedAt to null, so the shared_link never expires?

**Comment by mattwiller** [comment]
@barakbd It is not possible to create a shared link on upload — you'll need to make an `update()` call to add it.  Also, it is not currently possible to control the shared link expiration value via the API.

**Comment by barakbd** [comment]
As Promised here is an example of my code. Using Typegoose and Multer.
As a next step improvement I would like to simply pipe the request to the Box aPI (not using the SDK). Multer slows the upload, since it buffers the whole file into memory before the file is ready to use. There is an option to create a StorageEngine in Multer, however, it is simpler to just use native NodeJS pipe() and http.request. Just need to set the correct request options and headers.

``` typescript

import {
  Router,
  Request,
  Response,
  NextFunction,
  RequestHandler
} from "express";
import * as mongoose from "mongoose";
import { File, FileModel } from "../models/File";

//Needed for handling files
import * as multer from "multer";
import { InstanceType } from "typegoose";
const upload: multer.Instance = multer({ storage: multer.memoryStorage() });

class FileRoutes {
  static instance: FileRoutes;
  private _router: Router;
  private _boxClientLocal: any;

  constructor(boxClient: any) {
    this._boxClientLocal = boxClient;
    this._router = Router();
    //Routes
    this._router.post(
      "/:target_folder_id",
      upload.single("file"),
      this._create
    );
  } //end constructor

  //return singleton
  static getRouter(boxClient: any): Router {
    this.instance === undefined
      ? (this.instance = new FileRoutes(boxClient))
      : (this.instance = this.instance);
    return this.instance._router;
  }

  /******************* PRIVATE METHODS ****************/
  private _create: RequestHandler = (
    req: Request,
    res: Response,
    next: NextFunction
  ): Response => {
    // const file: Express.Multer.File = req.file;
    // const fileBuffer: Buffer = file.buffer; - informative

    return this._boxClientLocal.files
      .uploadFile(
        req.params.target_folder_id,
        req.file.originalname,
        req.file.buffer
      )
      .then((uploadFileSuccess: any) => {
        this._boxClientLocal.files
          .update(uploadFileSuccess.entries[0].id, {
            shared_link: this._boxClientLocal.accessLevels.DEFAULT
          })
          .then((updatedFileCuccess: any) => {
            let newFile: InstanceType<File> = new FileModel();
            newFile.metadata = updatedFileCuccess;
            newFile
              .save()
              .then((newFileSaveSuccess: InstanceType<File> | Document) => {
                res.status(200).json(newFileSaveSuccess);
              });
          })
          .catch((newFileSaveError: mongoose.Error) => {
            // next(newFileSaveError);
            return res.status(400).json(newFileSaveError);
          })
          .catch((updateFileError: any) => {
            return res.status(updateFileError.statusCode).json(updateFileError);
          });
      })
      .catch((uploadError: any) => {
        return res.status(uploadError.statusCode).json(uploadError);
      });
  }; //end _create

} //end class FileMethods

export default (boxClient: any): Router => {
  return FileRoutes.getRouter(boxClient);
};
```

**Comment by mattwiller** [comment]
@barakbd Thanks for posting your sample code!
