### ISSUE TITLE
Can't see pending collaboration object information

### ISSUE THREAD

**Issue by kalew8** [box/box-node-sdk#245]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I'm trying to get back collaboration information for a specific collaboration object, but the "accessible_by" object comes back null because the collaboration object is still "pending". I would like a way to see the email associated with the collaboration object even if it is pending, the same way you can see what email is pending in the Box GUI.

### Versions Used
Node SDK: v1.14.1
Node.js: v8.10.0

**Comment by mattwiller** [comment]
@kalew8 Unfortunately, the API does not support viewing the information for a pending collaborator.  This is a known feature gap between the API and the webapp, and boils down to security concerns with showing you the information of a user who has not accepted the invite to collaborate with you.  I'll file a ticket with the team who owns that API endpoint, but for now there isn't a way to get that information via the API.

**Comment by kalew8** [comment]
@mattwiller Gotcha. Thank you for the quick response.
