### ISSUE TITLE
Fetching Tags , Description , Versions of a File

### ISSUE THREAD

**Issue by sagardew** [box/box-node-sdk#248]
Hi @mattwiller ,

1. Is there any way we can upload and fetch Tags on a file, 
2. Posting Description of a file, i am able to fetch description but can not upload any.
3. Fetching Version of a File?

Also , when i upload a file through SDK the png file type over in box is shown as "File type", is there anything i am missing on? . I am taking file path and passing it through a stream

**Comment by mattwiller** [comment]
1. Tags are a [field on the file object](https://developer.box.com/v2.0/reference/#file-object) that is not returned by default.  You can request this field specifically by adding the `fields` option to your [`files.get()`](https://github.com/box/box-node-sdk/blob/master/docs/files.md#get-a-files-information) call to get the file information:
```js
client.files.get(fileID, {fields: 'name,description,tags'})
	.then(file => console.log(file));
```
2. You can add a description to a file with the [`files.update()`](https://github.com/box/box-node-sdk/blob/master/docs/files.md#update-a-files-information) method, just pass it as a field to be updated:
```js
client.files.update(fileID, {description: 'My file description'})
	.then(updatedFile => console.log(updatedFile));
```
3. There's a method to [get information about previous versions of a file](https://github.com/box/box-node-sdk/blob/master/docs/files.md#get-file-versions), as well as for [downloading the content of a previous version](https://github.com/box/box-node-sdk/blob/master/docs/files.md#download-a-previous-version-of-a-file).

I'm not sure that I understand your last question about the png file type — could you maybe show me the code you're trying to run, what it does, and what you think it should do instead?

**Comment by sagardew** [comment]
Hi @mattwiller ,

Thanks for quick response. Can i update the tags to a file the same way as of description?
And for point 3 :- i only need the file's current version number . example :- 
A.png v6   , how can i get the v6

**Comment by mattwiller** [comment]
@sagardew  Yes, you can update tags the same way as description.  The version number is something you'll need to compute yourself from the API response — in general, the current version number of the file is the number of previous versions plus one.  So, you should be able to do something like this:

```js
client.files.getVersions(fileID)
	.then(previousVersions => {
		var versionNumber = previousVersions.total_count + 1;
	});
```

**Comment by sagardew** [comment]
Thanks @mattwiller  !
