### ISSUE TITLE
Limit search to anscetor_folder_id and not subfolders

### ISSUE THREAD

**Issue by barakbd** [box/box-node-sdk#257]
- [X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
How can I search only within folder_id 0 and not subfolders?

### Versions Used
Node SDK: 1.2.1
Node.js: v9.4.0

### Steps to Reproduce
``` typescript
    this._boxClientLocal.search
      .query(req.query.name, {
        type: "folder",
        ancestor_folder_ids: 0
      })
```

### Error Message, Including Stack Trace
returns results in folder_id 0 as well as subfolders
Can I tag any folder I create in folder_id 0, and filter my search by that tag?

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@barakbd Unfortunately, there is no way to do that today with the Search API.  If you want to get a single item by name from the root folder, you would need to do one of the following:

1. Use the Search API like you're doing today and loop through the results to find the one you want
2. Just get the list of items in the root folder and loop through them to find the one you want
3. Wait for the Get Item By Path API to be finalized (hopefully in the next month or so) and use that to get the item directly by name
