### ISSUE TITLE
Questions about Chunk Upload API

### ISSUE THREAD

**Issue by RohanKurane** [box/box-node-sdk#261]
Hello,
I have a few questions regarding the new BOX Chunk Upload API. I am using C++ so I am not sure where to ask this question. Hopefully someone can move it to the right place.

1. For the UPLOAD PART what is the body of the request ? I noticed in the shell and cURL examples that --data-binary @part-name is specified at the end. Is this the file content of the part been uploaded ? So would my request body be something like below where filebytes_str is the content of the part ? 
std::string body;
  {
     std::string body = "{\"part_content\":\"" + filebytes_str + "\"}"
  }

And is this what I would send as the request after adding the right header fields ?
RestClient::Response resp = this->put(url,body);     or would it be 
RestClient::Response resp = this->put(url,filebytes_str);   ?     

2. For LIST PARTS I am suppose to get a list of all parts that are to be committed in a json array of objects. Since I am using C++ here, how can I convert the json array of objects to a std::string to pass to the request body in the COMMIT UPLOAD part ?   --> I used rapidjson to convert the json array of objects to std::string type. Is this okay ?

@mattwiller  @carycheng

**Comment by mattwiller** [comment]
@RohanKurane This repo is for our Node.js SDK; we're not really experts in C++ and aren't equipped to answer your questions here.  You should try posting over at the [Box Developer Forum](https://community.box.com/t5/Box-Developer-Forum/bd-p/DeveloperForum) — someone there might have more expertise in what you're trying to do.
