### ISSUE TITLE
Add an option to getRepresentationInfo to start request

### ISSUE THREAD

**Issue by holbrookab** [box/box-node-sdk#265]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
In the API, getting a file's representation info returns an object called `status`.  If the status's state is `none`, then Box won't create the representation until you make a GET request to the url in the `info` object.  It'd be great if, when you run `getRepresentationInfo` function, if the status is `none`, it kicked off the process by making the request.

### Versions Used
Node SDK: 1.16.0
Node.js: 8.9.4
[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs

**Comment by holbrookab** [comment]
It looks like you use `pollRepresentationInfo` for `getRepresentationContent` but not for `getRepresentationInfo`.  I was able to add that to `getRepresentationInfo`, although it does change the usability slightly: only one representation info object would be returned.

For reference, why I need it in the `getRepresentationInfo` call, is the info's metadata returns the number of available pages.  That isn't returned until the representation processing is complete.

**Comment by holbrookab** [comment]
[Here](https://github.com/holbrookab/box-node-sdk/tree/repinfo-polling), although I'm failing two tests.

Test 1:
> getRepresentationInfo()
> 
> should call callback with the representation when a 200 response is returned:
> Uncaught Error: Unexpected API Response [undefined undefined]

Test 2:
> getRepresentationInfo()
>
> should return a promise resolving to a representation object when a 200 response is returned:
> Error: Unexpected API Response [undefined undefined]

Did I do something wrong with the `then`,`then`,`asCallback` lines in the [getRepresentationInfo](https://github.com/holbrookab/box-node-sdk/blob/repinfo-polling/lib/managers/files.js#L1367)?

**Comment by mattwiller** [comment]
@holbrookab The idea of `getRepresentationInfo()` is that it gives you the status of the representations as they are; if you want to kick off the generation of a representation you can do it yourself by feeding the representation info URL to `client.get()`, like this:

```js
client.files.getRepresentationInfo(fileID, repHints)
	.then(representations => {
		var repInfo = representations.entries.find( /* pick which rep you want... */ );
		if (repInfo.status.state === 'none') {
			return client.get(repInfo.info.url);
		}
		return repInfo; 
	})
	.then(repInfo => {
		// repInfo should have status.state 'pending' or 'success' or 'viewable' here
	});
```

Unfortunately, we won't be able to accept your changes as they are now — the code on your branch makes a backwards-incompatible change to the contract of `getRepresentationInfo()` and makes it only return the first representation in the result set, instead of the entire set.

**Comment by holbrookab** [comment]
Yup, makes sense.  It's just a shame because this would be good in the API, and you already have that polling code.  To me, it also seems like it'd be a helpful function as part of the API.

What about tweaking the polling function, and exposing an explicit `pollRepresentationInfo` function, a la [this](https://github.com/holbrookab/box-node-sdk/blob/repinfo-polling2/lib/managers/files.js#L1409).

**Comment by mattwiller** [comment]
Hi @holbrookab — we just added the `generateRepresentations` option to `getRepresentationInfo()` in v1.19.0 of the SDK.  Please give it a try and let us know how it works for you!
