### ISSUE TITLE
app auth developer token

### ISSUE THREAD

**Issue by barakbd** [box/box-node-sdk#270]
Is it possible to get a temporary developer token for an App Auth Client?
When I go to the Developer Console and generate a token, it provides a token for the user who owns the App Auth client.

**Comment by mattwiller** [comment]
@barakbd The Developer Token is for testing only — if you want to make API calls as the Service Account or App Users, you'll need to go through the [JWT auth process](https://github.com/box/box-node-sdk/blob/master/docs/authentication.md#server-auth-with-jwt)
