### ISSUE TITLE
Add an option to create a basic client without initializing a dummy

### ISSUE THREAD

**Issue by cbetta** [box/box-node-sdk#276]
Currently, to initialize a BasicClient with an access token, you have to first initiallize a dummy SDK instance.

```js
let Box = require('box-node-sdk');
let box = new Box({
    clientID: 'unused',
    clientSecret: 'unused'
});
let client = box.getBasicClient(actualAccessToken);
```

This feels really redundant and ugly. Is there a chance we can simplify this by adding a "static" method to the BoxSDK class?

```js
let Box = require('box-node-sdk');
let client = Box.getBasicClient(actualAccessToken);
```

Under the hood, this could obviously do the same as the first code sample, but it would make all client code a lot cleaner and simpler.

**Comment by mattwiller** [comment]
Closing since #278 is merged 🎉 — this will go out with the next release, tentatively scheduled for tomorrow
