### ISSUE TITLE
JWT Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by rikrok** [box/box-node-sdk#288]
Hey all, thanks for taking a time to check this out. I'm not entirely sure where I'm going wrong, but I'm really confused as to what I'm doing incorrectly. 

- [X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I'm having a slight issue with authenticating with a JWT JSON file or passing it as a hard coded string. It seems that there is a parsing issue with the Private Key and I have no idea how to overcome this.

Here's the code:

```
var BoxSDK = require('box-node-sdk');
var jsonConfig = require('../data/boxconfig.json');
var sdk = BoxSDK.getPreconfiguredInstance(jsonConfig);

var serviceAccountClient = sdk.getAppAuthClient('enterprise');

serviceAccountClient.users.get(serviceAccountClient.CURRENT_USER_ID)
    .then(user => console.log('Hello', user.name, '!'))
    .catch(err => console.log('Got an error!', err));
```

Here's the json file (XXX's replace actual values). Note that removing the \n will result in 
`"Cannot read property '2' of null"`
```
{
  "boxAppSettings": {
    "clientID": "xxxxxxxxxxxxxx",
    "clientSecret": "xxxxxxxxxxxxxx",
    "appAuth": {
      "publicKeyID": "xxxxxxxxxxxxxx",
      "privateKey": "-----BEGIN ENCRYPTED PRIVATE KEY-----\nxxxxxxxn-----END ENCRYPTED PRIVATE KEY-----\n",
      "passphrase": "xxxxxxxxxxxxxx"
    }
  },
  "enterpriseID": "xxxxxxxxxxxxxx"
}
```

The above is right from the JWT creation on box.com. It doesn't matter if I replace it with actual hardcoded characters or from the file, I get errors. All the strings work just as well in the .NET SDK version. 

### Versions Used
Node SDK: 1.19.0
Node.js: 6.1.0

### Steps to Reproduce
Try to use a JWT 

### Error Message, Including Stack Trace

Here's the error:
```
Got an error! TypeError: Cannot read property 'split' of undefined
    at decrypt (index.js?8e48:99)
    at parseKeys (index.js?8e48:52)
    at sign (sign.js?a67f:10)
    at Sign.signMethod [as sign] (index.js?29e3:41)
    at Object.sign (index.js?edf9:76)
    at Object.jwsSign [as sign] (sign-stream.js?87e9:32)
    at Object.module.exports [as sign] (sign.js?b972:188)
    at TokenManager.getTokensJWTGrant (token-manager.js?15e1:325)
    at AppAuthSession._refreshAppAuthAccessToken (app-auth-session.js?2a42:86)
    at AppAuthSession.getAccessToken (app-auth-session.js?2a42:138)
    at BoxClient._makeRequest (box-client.js?6a32:291)
    at BoxClient.get (box-client.js?6a32:520)
    at wrappedClientMethod (box-client.js?6a32:729)
    at Users.get (users.js?1195:57)
    at Object.getUser (box.js?b073:12)
    at VueComponent.getUser (VM9158 landSearch.vue:11)
```

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs

**Comment by rikrok** [comment]
Thanks for the quick reply @mattwiller! 

Versions Used
Node SDK: 1.19.0
Node.js: 6.1.0

I am using **vuejs webpack** though.  The browser I'm running is Chrome Version 67.0.3396.87 (Official Build) (64-bit) with **Windows 10** .

Manually setting the configuration options in the SDK results in the same behavior :(

**Comment by mattwiller** [comment]
@rikrok Unfortunately, the Node.js SDK does not currently support running in a browser via Webpack.  When Webpack bundles the SDK, it needs to polyfill various Node.js modules that the SDK depends on, in this case especially `crypto`.  We can't make any guarantees about how [the polyfill](https://github.com/crypto-browserify/crypto-browserify) behaves, and it looks like that's where the issue you're seeing is coming from.

**Comment by rikrok** [comment]
Apologies for the late reply! Thanks for your explanation of what was happening!
