### ISSUE TITLE
Missing values in Webhooks.prototype.triggerTypes

### ISSUE THREAD

**Issue by MathersMax** [box/box-node-sdk#292]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
It seems that some trigger types are missing from your enum

### Versions Used
Node SDK: 1.19.0
Node.js: Not relevant

### Error Message, Including Stack Trace
The following values seems to be missing from the `Webhooks.prototype.triggerTypes` enum in `lib/managers.webhooks.js` : 

- `FILE.RENAMED`,
- `FOLDER.TRASHED`,
- `FOLDER.RENAMED`,
- `COLLABORATION.CREATED`,
- `COLLABORATION.ACCEPTED`,
- `COLLABORATION.REJECTED`,
- `COLLABORATION.REMOVED`,
- `COLLABORATION.UPDATE`,
- `SHARED_LINK.DELETED`,
- `SHARED_LINK.CREATED`,
- `SHARED_LINK.UPDATED`

I have forked the repository and can create a pull request if you want.

Best regards

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @MathersMax, 

Thank you for writing in! If it's not too much trouble we always welcome pull requests! 

Otherwise, we are more than happy to patch this as well

Much appreciated!

**Comment by MathersMax** [comment]
My pleasure. Doing this first time tomorrow morning.

**Comment by carycheng** [comment]
reference #293
