### ISSUE TITLE
Display app name of service account

### ISSUE THREAD

**Issue by barakbd** [box/box-node-sdk#297]
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
How do I get the app name?
I am using var serviceAccountClient = sdk.getAppAuthClient('enterprise', 'APP_ENTERPRISE_ID');
Then serviceAccountClient.users.get("me", null)

But this returns the user who owns the service account, not the service account itself.

**Comment by carycheng** [comment]
Hey @barakbd, 

Unfortunately that is not possible, may I ask why you wish to retrieve the app name for the service count? Maybe there is another approach we can help with 

Thanks!

**Comment by barakbd** [comment]
Since 1 user may have multiple apps, It would be intuitive to know which app credentials the SDK is running for. If you only show the user, it is impossible to tell which service account is running.

**Comment by mattwiller** [comment]
@barakbd This information is not exposed via the API, but since the app credentials are passed in when you instantiate the SDK you should be able to know which ones are in use at any given time.
