### ISSUE TITLE
cascading metadata api not implemented

### ISSUE THREAD

**Issue by kendomen** [box/box-node-sdk#301]
I don't see the cascading metadata (https://developer.box.com/v2.0/reference#get-metadata-cascade-policies) implemented in here.  Is this true?

thanks!
Ken

**Comment by mattwiller** [comment]
@kendomen We have a PR open to add this API — #269 — but hadn't merged it yet because the API was not yet considered stable (it's still in beta).  We just got word that the API should now be stable, and will be targeting Thursday for releasing support for the new endpoints!

**Comment by mattwiller** [comment]
@kendomen We just released v1.20.0 of the SDK, which includes support for Metadata Cascade Policies!  Please let us know if you run into any issues.

**Comment by mattwiller** [comment]
@kendomen The API docs note that you may get a 403 error if your enterprise is not added to the beta for Metadata Cascade Policies.  Does that call work for you if you attempt in manually in a tool like Postman or curl?
