### ISSUE TITLE
event stream destruction

### ISSUE THREAD

**Issue by boneskull** [box/box-node-sdk#302]
There doesn't seem to be any way to *stop* an `EventStream` from continually long-polling once started, short of killing the Node.js process.

In Node.js v8.x or later I think you want to implement the `Readable` stream's `_destroy()` (much like you would with `_read()`) method.

For Node.js pre-v8.x, generally it looks like you're going to want to *wrap* `Readable#destroy()`.  So a solution might look like this:

```js
EventStream.prototype._destroy = function() {
  // if this is v8.x+ and `EventStream#destroy()` was called, then 
  // `this.destroyed` will be true.  if it isn't, then call it,
  // since we probably got here via `MyStream#abort()`.
  // `Readable#destroy()` sets `this.destroyed` to `true`.
  if (!this.destroyed) {
    this.destroy();
  }
  // shut down long polling
});

EventStream.prototype.abort = EventStream.prototype._destroy;
```

My use-case:  I'm implementing event streams in a [Node-RED](https://nodered.org) addon, which will otherwise leak memory and resources.

Hopefully this sounds OK; I have an implementation and tests which I'll send as soon as tomorrow.

**Comment by mattwiller** [comment]
@boneskull Sounds good to me — I look forward to reviewing your implementation!

**Comment by mattwiller** [comment]
@boneskull The functionality you added was just release in v1.12.0 of the SDK — thanks again for the PR!
