### ISSUE TITLE
Unable to handle events from Readable Stream client.files.getReadStream()

### ISSUE THREAD

**Issue by denseflux** [box/box-node-sdk#316]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue

I'm trying to do a partial download of a file.

Having read the documentation for downloading files I was expecting getReadStream to return the first 2048 bytes from the file as a readable stream, but I get an error with the event. My code is:

```
    const readable = client.files.getReadStream(fileId,{byteRange: [0, 2048] },function(error, stream) {
        if (error) {
            console.log("an error occurred!", error);
        }
    })

readable.on('data', (chunk) => {
  console.log(`Received ${chunk.length} bytes of data.`);
});
```

### Versions Used
Node SDK: 1.20.0
Node.js: 8.1

### Error Message, Including Stack Trace

```
    readable.on('data', (chunk) => {
             ^

TypeError: readable.on is not a function
    at Object.<anonymous> (/mnt/c/Users/Steve/www/box/app1/readable_stream.js:23:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@denseflux The [getReadStream() docs](http://opensource.box.com/box-node-sdk/jsdoc/Files.html#getReadStream) indicate that the method returns a `Promise` resolving to the Readable and not the `Readable` itself.  You'll need to do something like this:

```js
const readable = await client.files.getReadStream(fileId,{byteRange: [0, 2048] });
```
