### ISSUE TITLE
Get metadata output does not match documentation.

### ISSUE THREAD

**Issue by grugknuckle** [box/box-node-sdk#325]
- [x ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue. 

### Description of the Issue
The output from the `client.files.getAllMetadata(fileID)` method is not returning the data as it is [described in the documentation](https://github.com/box/box-node-sdk/blob/master/docs/metadata.md#get-metadata-on-a-file). I'm not sure if this is an issue with the documentation or if it is an issue with the code base.

Per the [documentation](https://github.com/box/box-node-sdk/blob/master/docs/metadata.md#get-metadata-on-a-file) of the getAllMetadata method, the method returns a promise, which, when it is resolved successfully, should give data of the form

```
client.files.getAllMetadata('11111')
	.then(metadata => {
		/* 
                metadata -> {
			entries: 
			[ 
			     { first template },
			     { second template },
			     ...
			]
	          }
                 */
        })
```
But instead, I am receiving details about the request with the data. With my code as follows, 
```
client.asUser('6050790110').files.getAllMetadata('352959200438')
```
My output is as below. The content of the "buffer" field is correct and matches my expected output of the "entries" field as described in the documentation.
```
{
    "nextField": "marker",
    "nextValue": null,
    "limit": 100,
    "done": true,
    "options": {
        "headers": {
            "User-Agent": "Box Node.js SDK v1.22.0 (Node v8.12.0)",
            "As-User": "6050790110",
            "X-Box-UA": "agent=box-node-sdk/1.22.0; env=Node/8.12.0",
            "accept": "application/json"
        },
        "qs": {
            "marker": null
        }
    },
    "buffer": [
        { my-metadata-template}
    ],
    "queue": {
        "options": {},
        "pendingPromises": 0,
        "maxPendingPromises": 1,
        "maxQueuedPromises": null,
        "queue": []
    }
}
```

### Versions Used
You can see the versions in the output above.

EDIT: After updating my node_modules `npm update box-node-sdk`, I am now running v1.22.1 of the SDK and the issue persists.

**Comment by carycheng** [comment]
Hey @grugknuckle, 

Is this the only call you are seeing this behavior of requests mixed in with the output?

I just attempted the `getAllMetadata()` call with `asUser()` and it seems to be outputting okay with this

```node
client.asUser('12345')
client.files.getAllMetadata('56781').then(console.log)
```

The output format was similar to the expected from the docs with information redacted.
```
{ entries: 
   [ { '$type': '',
       '$parent': 'file_302145369927',
       '$id': '',
       '$version': 1,
       '$typeVersion': 1,
       accountname: 'Random File',
       '$template': 'account',
       '$scope': 'enterprise_12345',
       '$canEdit': true },
     { cards: [Array],
       '$type': '',
       '$parent': '',
       '$id': '',
       '$version': 0,
       '$typeVersion': 2,
       '$template': '',
       '$scope': 'global',
       '$canEdit': true },
     { foo: 'bar',
       '$type': 'properties',
       '$parent': '',
       '$id': '',
       '$version': 0,
       '$typeVersion': 5,
       '$template': 'properties',
       '$scope': 'global',
       '$canEdit': true } ],
  limit: 100 }
```

Would love to know if this is across all calls you are making with the SDK?

**Comment by carycheng** [comment]
Apologies, clicked the wrong submit button.

@grugknuckle, please let us know from the above!

**Comment by mattwiller** [comment]
@grugknuckle It looks like you've configured the SDK with `iterators: true` — this causes it to return an iterator over the collection rather than the raw JSON, as documented.  If you want it to return the raw JSON, simply remove that value from the SDK configuration.
