### ISSUE TITLE
Is any feature in box-node-sdk for merge two document for edit document?

### ISSUE THREAD

**Issue by C271030** [box/box-node-sdk#331]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
// Replace this text with a description of what problem you're having.  
// Please include as much detail as possible to help us troubleshoot!  
// If it isn't obvious, please include how the behavior you expect differs from what actually happened.  
// This is really important so we know how to start troubleshooting your issue
Is any api is available in box-node-sdk to edit document or merge two document at server ?
### Versions Used
Node SDK: // Replace with the version of the Node SDK you're using.  
Node.js: // Replace with the version of Node.js your application is running on.

### Steps to Reproduce
// Please include detailed steps to reproduce the issue you're seeing, if possible.  
// If you don't have a reproducible error, please make sure that you give us as much detail  
// as you can about what your application was doing when the error occurred.  
// Good steps to reproduce the problem help speed up debugging for us and gets your issue resolved sooner!

### Error Message, Including Stack Trace
// Replace with the full error output you're seeing, if applicable.  
// Please include the full stack trace to help us identify where the error is happening.

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs

**Comment by jasonpan12** [comment]
Hey @C271030, that's not available in the base API unfortunately. You can certainly upload a document as a new version of another, but there's no feature for merging the content of a file with another file.
