### ISSUE TITLE
Finding a file by filename

### ISSUE THREAD

**Issue by dcods22** [box/box-node-sdk#344]
- [X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
// Replace this text with a description of what problem you're having.  
// Please include as much detail as possible to help us troubleshoot!  
// If it isn't obvious, please include how the behavior you expect differs from what actually happened.  
// This is really important so we know how to start troubleshooting your issue.

I was wondering if there is a way to find a file by filename.  I know the name of the file and the parent ID but the only way I can seem to find it is by searching through the folder and often then since our names are very similar on multiple files I need to iterate through the results.  I was hoping to get a file's ID by just saying getFile("name", folderId).  I could not find anything about this in the documentation.

### Versions Used
Node SDK: // Replace with the version of the Node SDK you're using.  
Node.js: // Replace with the version of Node.js your application is running on.

1.25.0

### Steps to Reproduce
// Please include detailed steps to reproduce the issue you're seeing, if possible.  
// If you don't have a reproducible error, please make sure that you give us as much detail  
// as you can about what your application was doing when the error occurred.  
// Good steps to reproduce the problem help speed up debugging for us and gets your issue resolved sooner!

### Error Message, Including Stack Trace
// Replace with the full error output you're seeing, if applicable.  
// Please include the full stack trace to help us identify where the error is happening.

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@dcods22 The best way to do this today would be to use the [Search API](https://developer.box.com/v2.0/reference/#searching-for-content) to try and find an exact match; please take a look over our [documentation for how to call the Search API through the SDK](https://github.com/box/box-node-sdk/blob/master/docs/search.md).  Something like this should do what you want:

```js
var filename = 'PUT_FILENAME_HERE'; // Filename without extension
var fileExtension = 'PUT_FILE_EXTENSION_HERE'; // No dot, e.g. 'pdf'
var parentFolderID = 'PUT_PARENT_FOLDER_ID_HERE';

var searchOptions = {
    file_extensions: fileExtension,
    ancestor_folder_ids: parentFolderID,
    content_types: 'name',
    type: 'file',
};

var query = '"' + filename + '"'; // Use quoted query to get exact matches only

client.search.query(query, searchOptions)
	.then(results => {
        var file = results.find(f => f.name === filename + '.' + fileExtension && f.parent.id === parentFolderID);

		// `file` should point to the exact file you're looking for
    });
```

**Comment by dcods22** [comment]
Awesome thanks so much that worked.
