### ISSUE TITLE
Support for customizing folder/file name on Copy

### ISSUE THREAD

**Issue by kmcroft13** [box/box-node-sdk#40]
I'd like to see support for customizing the names of items during a Copy process. The Box API allows for specifying the new item name as an optional parameter in the request (see below), but this is not currently supported in the SDK. Can an optional parameter be added to the Folder Copy and File Copy functions to support this?

Folder Copy: https://docs.box.com/reference#copy-a-folder
File Copy: https://docs.box.com/reference#copy-a-file

Thanks!

**Comment by mattwiller** [comment]
This parameter can definitely be added, although we'll need to support both the new and old copy method signatures so we don't break backward compatibility.
