### ISSUE TITLE
JTI claim value is not getting regenerated if any API calls fails due to rate limit

### ISSUE THREAD

**Issue by braj1999** [box/box-node-sdk#403]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
We are using box-node-sdk v 1.29.0 in our application. The application is designed to discover all the files inside a folder and download the files found inside it. To achieve this, we to first API call to get the list of files inside the given folder and for each of the file discovered, we do one more API call to get details.

The code looks like below:

```
    var session = boxNodeSDK.getPreconfiguredInstance(this.getDataSource().connector.OAuth2_JWT_config);
    var serviceAccountClient = session.getAppAuthClient('user', userId);
    serviceAccountClient.files.get(fileId, {}, function(err, fileInfo) {
```
we observed that above code fails randomly with below error. upon reading further on this error, we are of understanding that this is due to rate limits being hit inside SDK.

```
{"error":"invalid_grant","error_description":"Please check the 'jti' claim. A unique 'jti' value is required."}
```

Could someone please help us understand if there is any way we can handle this condition using a retry strategy.

### Versions Used
Node SDK: 1.29.0
Node.js: 8.15.1

### Steps to Reproduce
The steps to reproduce would be to have an application making API calls at a very fast pace to Box.

### Error Message, Including Stack Trace
```
{"error":"invalid_grant","error_description":"Please check the 'jti' claim. A unique 'jti' value is required."}
```

**Comment by mattwiller** [comment]
@braj1999 It looks like maybe the API is marking the `jti` claim as seen even in scenarios where the request is rate limited and the authentication was not actually granted.  We should be able to add better retry behavior in the SDK to generate a new `jti` claim for this case, which I think should help resolve the issue you're seeing.  I'll update this ticket with a PR in the next few days once I've figured out exactly what's going on!

**Comment by braj1999** [comment]
thanks @mattwiller Any ETA that you can share with us.

**Comment by mattwiller** [comment]
@braj1999 I just opened PR #405 to address this issue; we should be able to get the fix into the next SDK release later this week

**Comment by mattwiller** [comment]
@braj1999 We just pushed out v1.29.1 with the fix for this issue — please check it out and let us know if you have any further difficulties!

**Comment by braj1999** [comment]
thanks @mattwiller
