### ISSUE TITLE
error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by shivaallani7** [box/box-node-sdk#409]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Detailed Error: 
1. I am manually giving the private key to the new BoxSDK( ) instance. I have generated the key from the Box-developer console.
2. I am able to print the sdk.CURRENT_USER_ID on the console. I assume sdk instantiated properly. but it is throwing me the error while calling the below method:

sdk.getEnterpriseAppAuthTokens("XXXXXXXX", null, function(error, token) {
  console.log("service account token", token.accessToken);
  saToken = token.accessToken;
});
3. if the sdk is not instantiated properly even the statement **sdk.CURRENT_USER_ID** should not be working.

Please find the part of the code i am using below:
**var sdk = new BoxSDK({
    clientID: 'XXXXX',
    clientSecret: 'XXXXXX',
    appAuth: {
        keyID: '1wa6bxnh',
        privateKey: '-----BEGIN ENCRYPTED PRIVATE KEY-----XXXXXXXEND ENCRYPTED PRIVATE KEY-----',
        passphrase: 'XXXXXXX'
    }
});

var serviceAccountClient = "";
serviceAccountClient = sdk.getAppAuthClient("enterprise", "XXXXX");

function waitForResponse() {
    return new Promise(function(resolve, reject) {
        setTimeout(resolve, 500);
    })
}

callSdk();

var check = "";

    //Wait for function to respond 
    while (check === "") {
         await waitForResponse();
    }

////////////GET SERVICE ACCOUNT///////////////////
var appUserToken;
var appUserClient;
var saToken;
var userId;

function callSdk() {
    console.log(" In get service account token method");
    sdk.getEnterpriseAppAuthTokens("226734682", null, function(error, token) {
        if(error)
        {
            console.log(error);
            check = "error";
            return;
        }
        else {
            console.log("token : " + token);
            console.log("service account token", token.accessToken);
            check = "success";
            saToken = token.accessToken;
            return;
        }
    });

    
}**

### Versions Used
Node SDK: 
Node.js: 

### Error Message, Including Stack Trace
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Sign.sign (internal/crypto/sig.js:82:26)
    at Object.sign (/app/node_modules/jwa/index.js:152:45)
    at Object.jwsSign [as sign] (/app/node_modules/jws/lib/sign-stream.js:32:24)
    at Object.module.exports [as sign] (/app/node_modules/box-node-sdk/node_modules/jsonwebtoken/sign.js:204:16)
    at TokenManager.getTokensJWTGrant (/app/node_modules/box-node-sdk/lib/token-manager.js:325:20)
    at BoxSDKNode.getEnterpriseAppAuthTokens (/app/node_modules/box-node-sdk/lib/box-node-sdk.js:338:27)
    at callSdk (Planet9ServerScript_ServiceAccount-box:41:9)
    at Promise (Planet9ServerScript_ServiceAccount-box:19:1)
    at new Promise (<anonymous>)

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@shivaallani7 Does your `privateKey` string have newline (`\n`) characters in it, especially after the `-----BEGIN ENCRYPTED PRIVATE KEY-----` part?  I believe that formatting is required for OpenSSL to be able to correctly read the key.

**Comment by shivaallani17** [comment]
> @shivaallani7 Does your `privateKey` string have newline (`\n`) characters in it, especially after the `-----BEGIN ENCRYPTED PRIVATE KEY-----` part? I believe that formatting is required for OpenSSL to be able to correctly read the key.

No. I have parsed the Key and removed all the (\n) in the key.

**Comment by mattwiller** [comment]
@shivaallani7 As I mentioned, those newlines are required for OpenSSL to parse the key; could you try adding them back and let me know if that resolves your issue?

**Comment by shivaallani17** [comment]
> @shivaallani7 As I mentioned, those newlines are required for OpenSSL to parse the key; could you try adding them back and let me know if that resolves your issue?

Please correct me If I am wrong. If there is something wrong with the key.The statements **console.log(sdk.CURRENT_USER_ID)** should not work. But this statement is working and printing **me** as the current user.

**Comment by mattwiller** [comment]
@shivaallani7 `sdk.CURRENT_USER_ID` is a [static constant in the code](https://github.com/box/box-node-sdk/blob/563238d999f5cb56f6a177c0676e3611ea2ea536/lib/box-node-sdk.js#L126); its value is always the string `"me"`.  The issue you're seeing is likely due to the removal of the newline characters from the private key; could you try using the private key exactly as it was originally formatted and let me know if that resolves your issue?

**Comment by shivaallani17** [comment]
> @shivaallani7 `sdk.CURRENT_USER_ID` is a [static constant in the code](https://github.com/box/box-node-sdk/blob/563238d999f5cb56f6a177c0676e3611ea2ea536/lib/box-node-sdk.js#L126); its value is always the string `"me"`. The issue you're seeing is likely due to the removal of the newline characters from the private key; could you try using the private key exactly as it was originally formatted and let me know if that resolves your issue?

@mattwiller it is working. Thank you so much.

**Comment by mattwiller** [comment]
Perfect — glad it's working now! 🎉
