### ISSUE TITLE
TypeError: while creating service Account client

### ISSUE THREAD

**Issue by shivaallani7** [box/box-node-sdk#413]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Hello All,

I am trying to create the service Account client and getting the below error.
**TypeError: `[object Object]` is not an Option Object** at some internal box sdk methods.

what do you think I am making mistake. is it some thing wrong with box-module installation.
Please find the error stack and Code I have written below.

Thank you.

### Steps to Reproduce
**Code I am Using:**
await createServiceAccount();
async function createServiceAccount() {
        var BoxSDK = modules.box;
      var sdk = new BoxSDK({
    clientID: 'XXX',
    clientSecret: 'XXX',
    appAuth: {
        keyID: '1XX',
        privateKey: '-----BEGIN ENCRYPTED PRIVATE KEY-----\n\n-----END ENCRYPTED PRIVATE KEY-----\n',
        passphrase: 'XX'
    }
});
var serviceAccountClient = "";//sdk.getAppAuthClient("enterprise", "XX");
serviceAccountClient = sdk.getAppAuthClient("enterprise", "XX");
console.log(serviceAccountClient);
return serviceAccountClient;
}

  complete({createServiceAccount});

### Error Message, Including Stack Trace
error: Error when executing 'ServiceAccount_Orchards_box' TypeError: `[object Object]` is not an Option Object
    at module.exports (/app/node_modules/merge-options/index.js:156:10)
    at new Config (/app/node_modules/box-node-sdk/lib/util/config.js:151:20)
    at new BoxSDKNode (/app/node_modules/box-node-sdk/lib/box-node-sdk.js:92:16)
    at createServiceAccount (Server script "ServiceAccount_Orchards_box":-3:17)
    at Promise (Server script "ServiceAccount_Orchards_box":-6:7)
    at new Promise (<anonymous>)
    at Server script "ServiceAccount_Orchards_box":-9:16
    at Server script "ServiceAccount_Orchards_box":18:7
    at Script.runInContext (vm.js:104:20)
    at /snapshot/planet9/dist/cluster/scripts/executor.js:0:0
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/planet9/dist/cluster/scripts/executor.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Script 'ServiceAccount_Orchards_box' aborted with exit code null and signal 'SIGINT'. TypeError: `[object Object]` is not an Option Object
    at module.exports (/app/node_modules/merge-options/index.js:156:10)
    at new Config (/app/node_modules/box-node-sdk/lib/util/config.js:151:20)
    at new BoxSDKNode (/app/node_modules/box-node-sdk/lib/box-node-sdk.js:92:16)
    at createServiceAccount (Server script "ServiceAccount_Orchards_box":-3:17)
    at Promise (Server script "ServiceAccount_Orchards_box":-6:7)
    at new Promise (<anonymous>)
    at Server script "ServiceAccount_Orchards_box":-9:16
    at Server script "ServiceAccount_Orchards_box":18:7
    at Script.runInContext (vm.js:104:20)
    at /snapshot/planet9/dist/cluster/scripts/executor.js:0:0
    at Generator.next (<anonymous>)

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs

**Comment by shivaallani7** [comment]
Can some one answer the above question please .

Thank you.

**Comment by PJSimon** [comment]
Hi @shivaallani7,

I'll be taking a look at this issue for you.  I'll need some time to investigate.  I will get back to you within 24 hours an update.

Thanks!

**Comment by mattwiller** [comment]
@shivaallani7 I'm unable to reproduce your issue with the latest version (v1.29.1) of the SDK; I ran the following code and it worked fine on my machine:

```js
const BoxSDK = require('box-node-sdk');
const fs = require('fs');

let sdk = new BoxSDK({
	clientID: '[REDACTED]',
	clientSecret: '[REDACTED]',
	appAuth: {
		keyID: '[REDACTED]',
		privateKey: fs.readFileSync('./private_key.pem'),
		passphrase: '[REDACTED]'
	},
});

var client = sdk.getAppAuthClient('enterprise', '[REDACTED]')
```

Could you maybe try deleting your `node_modules` directory and re-installing your dependencies?

**Comment by shivaallani7** [comment]
Hi @mattwiller . we are currently using Neptune App development software with node js as the backend. we contacted Neptune Support.They informed us that their current version  some how could not accommodate Box-SDK.
This was their response below:
**Sorry, but this module will not work in version 1.0.24, you have to be on > v2. The reason for this is that in version 1 server scripts are executed in a separate context, for the most part this doesn't cause issues, however, in some cases it does. If the module does an equality check using instanceof, e.g. options instanceof Object, this will return false in version 1 because the module is required outside the server script context but the object passed as options is created inside the server script context. So even though the options object you are passing is in fact an object the equality check will return false making the module unusable in server scripts on version 1 of planet9. We have fixed this in version 2.**

is there any way we can bypass the situation they are explaining above and resolve the issue. does the Box provide any alternative ways to access the Box-SDk.

Thanks in Advance
SA

**Comment by mattwiller** [comment]
@shivaallani7 I would recommend updating to Neptune v2 if that's possible for you. 
 I'm not familiar with Neptune at all, so I'm not aware of any workarounds for using the SDK in that environment.

**Comment by PJSimon** [comment]
Hi @shivaallani7,  I'm going to close this old issue, but if you'd like us to continue to look into it, please just re-open the issue!  Thanks!
