### ISSUE TITLE
 Error: Auth Error: Please check the 'sub' claim. The 'sub' specified is invalid. [400 Bad Request] invalid_grant - Please check the 'sub' claim. The 'sub' specified is invalid.

### ISSUE THREAD

**Issue by shivaallani17** [box/box-node-sdk#418]
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Hi All,
I am trying to create the collaboration with User Id but it is giving me the below error. other methods were working fine except the collaboration. it is giving me the Auth error but the same Auth is working for other methods. Please find the error stack below:

### Steps to Reproduce
**Code I am Using.**
async function createCollaboration() {
  console.log(" in create collaboration");
  var options = {
    type: serviceAccountClient.itemTypes.FOLDER
  };
  serviceAccountClient.collaborations
    .createWithUserID(
      "10032442305",
      "10032442305",
      serviceAccountClient.collaborationRoles.EDITOR,
      options
    )
    .then(collaboration => {})
    .catch(error => {
      console.log(error);
    });
}

### Error Message, Including Stack Trace
    at Promise._settlePromises (e:\Box-app\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (e:\Box-app\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._settlePromise (e:\Box-app\node_modules\bluebird\js\release\promise.js:587:21)
    at Promise._settlePromise0 (e:\Box-app\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (e:\Box-app\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (e:\Box-app\node_modules\bluebird\js\release\promise.js:643:18)
    at e:\Box-app\node_modules\bluebird\js\release\nodeback.js:42:21
    at process.nextTick (e:\Box-app\node_modules\box-node-sdk\lib\api-request.js:347:3)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @shivaallani17,

Curious if you meant to do this but the first two parameters of ‘createWithUserID’ are userID and itemID, item referring to the item to collaborate on. I see that in the parameters you have passed the same identifier for bother user and item. This might be causing some issues please let us know what you see after updating those fields. 

Thank you!

https://github.com/box/box-node-sdk/blob/master/docs/collaborations.md#add-a-collaboration

**Comment by shivaallani17** [comment]
> Hey @shivaallani17,
> 
> Curious if you meant to do this but the first two parameters of ‘createWithUserID’ are userID and itemID, item referring to the item to collaborate on. I see that in the parameters you have passed the same identifier for both user and item. This might be causing some issues please let us know what you see after updating those fields.
> 
> Thank you!
> 
> https://github.com/box/box-node-sdk/blob/master/docs/collaborations.md#add-a-collaboration

**Comment by shivaallani17** [comment]
> > Hey @shivaallani17,
> > Curious if you meant to do this but the first two parameters of ‘createWithUserID’ are userID and itemID, item referring to the item to collaborate on. I see that in the parameters you have passed the same identifier for both user and item. This might be causing some issues please let us know what you see after updating those fields.
> > Thank you!
> > https://github.com/box/box-node-sdk/blob/master/docs/collaborations.md#add-a-collaboration

Hey @carycheng . sorry for that. I have the same issue even after changing the parameters.

**Comment by shivaallani17** [comment]
Hey @carycheng . I found the issue is in the service Account creation. Now I am getting the **Error : 404**
find the error stack below:
**    at Promise._settlePromise (e:\Box-app\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (e:\Box-app\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (e:\Box-app\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (e:\Box-app\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._settlePromise (e:\Box-app\node_modules\bluebird\js\release\promise.js:587:21)
  statusCode: 404,**


Thanks in Advance
SA

**Comment by carycheng** [comment]
@shivaallani17, this 404 most likely means your Service Account does not have permission on the folder you are trying to collaborate the user on. A Service Account does not have access to all files and folders in an enterprise by default, you will still have to invite the Service Account user into that folder you are trying to collaborate a user to.

More on Service Account [here](https://developer.box.com/docs/service-account). Please try first giving access to that folder for your Service Account and then try making the collaboration call with the userID you are attempting to collaborate.

Thank you!
