### ISSUE TITLE
Get Exchange token

### ISSUE THREAD

**Issue by Karthi-SRV** [box/box-node-sdk#434]
Get Exchange token

Name | Type | Attributes | Description
-- | -- | -- | --
accessToken | string |   | The valid access token to exchange
scopes | string \| Array.<string> |   | The scope(s) of the new access token
resource | string | <optional> | The absolute URL of an API resource to restrict the new token to
options | Object | <optional> | Optional parametersPropertiesNameTypeAttributesDescriptiontokenRequestOptionsTokenRequestOptions<optional>Sets optional behavior for the token grantactorActorParams<optional>Optional actor parameters for creating annotator tokens | tokenRequestOptions | TokenRequestOptions | <optional> | Sets optional behavior for the token grant | actor | ActorParams | <optional> | Optional actor parameters for creating annotator tokens

tokenRequestOptions | TokenRequestOptions | <optional> | Sets optional behavior for the token grant
actor | ActorParams | <optional> | Optional actor parameters for creating annotator tokens

lib/box-node-sdk.js

```
/**
 * Exchange a valid access token for one with a lower scope, or delegated to
 * an external user identifier.
 *
 * @param {string} accessToken - The valid access token to exchange
 * @param {string|string[]} scopes - The scope(s) of the new access token
 * @param {string} [resource] - The absolute URL of an API resource to restrict the new token to
 * @param {Object} [options] - Optional parameters
 * @param {Function} [callback] Passed the tokens if successful
 * @param {TokenRequestOptions} [options.tokenRequestOptions] - Sets optional behavior for the token grant
 * @param {ActorParams} [options.actor] - Optional actor parameters for creating annotator tokens
 * @returns {Promise<TokenInfo>} Promise resolving to the new token info
*/


BoxSDKNode.getExchangeToken = function(accessToken, scopes, resource, options, callback) {
	if (typeof options === 'function') {
		callback = options;
		options = null;
	}

	return this.tokenManager.exchangeToken(accessToken, scopes, resource, options)
		.asCallback(callback);
};
```

**Comment by Karthi-SRV** [comment]
Hi,
I have return the code snippets for exchange token api

https://developer.box.com/docs/customizing-access-for-box-ui-elements

It would be great, if you provide these api call for exchange the token .

**Comment by carycheng** [comment]
Hello @Karthi-SRV,

I wanted to double check on a couple of things - are you inquiring about the token exchange API and its availability in the Node SDK? If so we have it available and you can find documentation for it [here](https://github.com/box/box-node-sdk/blob/master/docs/authentication.md#token-exchange).

Let us know if this answers your question, thanks!
