### ISSUE TITLE
 PREVIEWER UPLOADER collaboration to folder

### ISSUE THREAD

**Issue by MartinRoman7** [box/box-node-sdk#449]
I'm trying to add a **PREVIEWER UPLOADER** collaboration to a Box folder using Node SDK.

Currently, I can create a folder with **UPLOADER** collaboration.

```
appUserClient.collaborations.createWithUserEmail(asistentes[i].email,id_nFolder,appUserClient.collaborationRoles.UPLOADER)
```

So, my question is about how to chande **UPLOADER** collaboration to **PREVIEWER UPLOADER **

I tried the following statement but I get an error, maybe because exists a space.

```


Regards
appUserClient.collaborations.createWithUserEmail(asistentes[i].email,id_nFolder,appUserClient.collaborationRoles.PREVIEWER UPLOADER)
```

**Comment by mattwiller** [comment]
@MartinRoman7 You're correct, the issue is that you have a space instead of an underscore.  The correct way to access this constant would be `appUserClient.collaborationRoles.PREVIEWER_UPLOADER`

**Comment by MartinRoman7** [comment]
@mattwiller Thanks a lot.

**Comment by PJSimon** [comment]
@MartinRoman7 I'm closing this as it appears resolved.  If that's not the case, please feel free to re-open!
