### ISSUE TITLE
Support for Range Headers for files.getReadStream()

### ISSUE THREAD

**Issue by loganweilenman** [box/box-node-sdk#45]
It was discovered in the API docs that the file download URL endpoint only supported version as a query string, while Range and BoxAPI is a header (Link: https://docs.box.com/reference#download-a-file) (initially listed Range, version, and BoxAPI all as acceptable query strings).

I'm wondering if the Node SDK will support the "Range" header as a param of the getReadStream() method, as "qs" was supposed to support the documented query strings from the API docs.

**Comment by mattwiller** [comment]
We're working on how to best support passing multiple types of parameters (e.g. query parameters, headers, etc) to a single API call, but for now you should be able to set headers from the client for that call:

```js
client.setCustomHeader('Range', 'bytes=0-100');
client.files.getReadStream(fileID, qs, callback);
```

Let me know if you run into problems with this approach!
