### ISSUE TITLE
how to auto grant/skip Oauth response page that grants user access to my application.

### ISSUE THREAD

**Issue by smithdavedesign** [box/box-node-sdk#491]
As the title says I am using box to authenticate a user, which takes them to box to authenticate him/herself. After the user logs in successfully it redirects to https://app.box.com/api/oauth2/authorize/......
which asks if they want to grant access to box. How can I skip/auto grant this page. It seams unnecessary for my users to grant access after they login.

**Comment by PJSimon** [comment]
Hi @smithdavedesign!

Thanks for reaching out! Unfortunately, this is not an Bug or Issue with the repo, so I would recommend that you reach out to the community for assistance, here: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum

Good luck!

@PJSimon
