### ISSUE TITLE
Explain how to get 'APP_ENTERPRISE_ID'

### ISSUE THREAD

**Issue by David-dp-** [box/box-node-sdk#500]
I have searched my enterprise https://app.box.com/account , https://developer.box.com/guides/ , https://community.box.com/t5/Platform-and-Development-Forum/ and googled, but haven't found an answer.

### Description of the Issue
https://github.com/box/box-node-sdk#app-auth-client mentions 'APP_ENTERPRISE_ID' but doesn't explain how one can find this value (assuming it's a placeholder and not a literal which I'm not totally sure of).

### Versions Used
Node SDK: N/A
Node.js: N/A

### Steps to Reproduce
N/A

### Error Message, Including Stack Trace
N/A

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/

**Comment by PJSimon** [comment]
Hi @David-dp- !

Thanks for reaching out!  Unfortunately, this is not an Bug or Issue with the repo, so I would recommend that you reach out to the community for assistance, here: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum

Good luck!

@PJSimon
