### ISSUE TITLE
Download file API is throwing `Error: socket hang up`

### ISSUE THREAD

**Issue by iamrahulroy** [box/box-node-sdk#503]
- [x ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Download file API is randomly throwing `Error: socket hang up`.

### Versions Used
Node SDK: 1.31.0
Node.js: 12.x

### Steps to Reproduce
Code snippet. https://developer.box.com/reference/get-files-id-content/
```
client.files.getReadStream(fileID, null, function(error, stream) {
  if (error) {
    console.log('Box getReadStream error:', error)
  }
  const output = fs.createWriteStream(outputFilePath);
  stream.pipe(output);
});
```

### Error Message, Including Stack Trace
Relevant stack trace:
```
Error: socket hang up [+33ms]
    at connResetException (internal/errors.js:604:14)
    at TLSSocket.socketCloseListener (_http_client.js:400:25)
    at TLSSocket.emit (events.js:323:22)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at net.js:668:12
    at TCP.done (_tls_wrap.js:556:7) {
  code: 'ECONNRESET',
  // ...
```

Is it a rate-limiting issue?

**Comment by PJSimon** [comment]
@iamrahulroy We'll take a look soon!  Thanks for reporting!

**Comment by iamrahulroy** [comment]
@PJSimon were you able to track down the issue?

**Comment by sujaygarlanka** [comment]
@iamrahulroy This seems like it could be a network issue on your end. This [issue](https://stackoverflow.com/questions/16995184/nodejs-what-does-socket-hang-up-actually-mean) occurs when a request times out. I would try making this call on a different network and see if it still occurs.
