### ISSUE TITLE
npm-upgrade should probably not be a dependency

### ISSUE THREAD

**Issue by dphrag** [box/box-node-sdk#509]
- [X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I was neurotically cleaning dependencies and noticed this SDK installs **npm-upgrade**. It's unused in code and should probably either be removed or changed to a devDependency.

**Comment by sujaygarlanka** [comment]
@dphrag Thanks for the feedback! Taking a look at this.
