### ISSUE TITLE
JWT Access To Shared Directories

### ISSUE THREAD

**Issue by stephencweiss** [box/box-node-sdk#513]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
After authorizing my application, my user, nor the Service Account user has access to a Box folder to which my user is a collaborator (my user also being the user associated with the App), though it does not work on all folders in my environment -- namely it does not work on any that have been shared with my enterprise (basically, the yellow folders below, not the "grey with globe")

![Screen Shot 2020-06-16 at 3 57 07 PM](https://user-images.githubusercontent.com/39878535/84827738-86fa9a80-afea-11ea-8fbd-590a21803378.png)

### Steps to Reproduce
1. Create a new custom app
2. Application Access = Enterprise (though I think default should be fine)
3. Application scope include `Read and write all files and folders stored in Box`
4. Advanced Features:
![Screen Shot 2020-06-16 at 3 50 14 PM](https://user-images.githubusercontent.com/39878535/84826770-13a45900-afe9-11ea-983e-31419794c464.png)
5. Generate a public/private keypair
6. Authorize the app
7. Run the app trying to find a folder _other_ than root 

Sample App:
https://repl.it/@stephencweiss/UnfinishedBulkyPercent
^^ Requires going at least through step 6 above to get a `config.json` file

### Expected Behavior
Acting as my user, I should be able to modify any directories in Box to which my user has privileges. I am an "Editor" on the grey ones -- why can I not programmatically access them?

### Error Message, Including Stack Trace
`Folder error: Error: Unexpected API Response [404 Not Found | fyh5ytgfutekwlgm.0bc0b1cd28f62db824c12e4c96ce9cca8] not_found - Not Found`

### Screenshots

My user's access within the "grey globe" folder:
![Screen Shot 2020-06-16 at 3 40 17 PM](https://user-images.githubusercontent.com/39878535/84828072-11db9500-afeb-11ea-8c00-604e24a57c62.png)

"Grey globe" folder shared with my user returns 404
![Screen Shot 2020-06-16 at 3 42 38 PM](https://user-images.githubusercontent.com/39878535/84828020-fa9ca780-afea-11ea-89c7-159fab7114e8.png)

Test folder (created by my user) works:
![Screen Shot 2020-06-16 at 4 03 03 PM](https://user-images.githubusercontent.com/39878535/84827987-ee184f00-afea-11ea-9c36-a7e02ca96371.png)

### Versions Used
Node SDK: "^1.32.0"

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by cbetta** [comment]
Hi @stephencweiss, in your code you seem to authenticate as the Service Account, while I think the folder is shared with your own personal account (aka managed user), right? If so, you need to actually act as that managed user to access that folder.

Now, you might know this already, but here is the detail that trips up people: there are 2 ways to act as another user using JWT, and only one of them will give access to externally shared folders.

You already enabled both the permissions for this:

* Perform actions as users
* Generate User Access Tokens

Only this second method can be used to access externally collaborated folders.

In your code, replace 

```js
const client = sdk.getAppAuthClient("enterprise")
```

with

```js
const client = sdk.getAppAuthClient("user", "[your_managed_user_id]")
```

Here, `[your_managed_user_id]` needs to be the ID of your managed user account, the one who the folder has been shared with.

**Comment by stephencweiss** [comment]
Thanks @cbetta!

I suspect you've diagnosed the problem correctly - so a few follow up questions:
1. Is there a way to _confirm_ that it is in fact a managed account? (The company set me up and all I see is this one user in my Admin Console)
![Screen Shot 2020-06-17 at 9 58 44 AM](https://user-images.githubusercontent.com/39878535/84914492-4863ef00-b081-11ea-8559-87e670a1441e.png)

2. For this part of your reply:
 
> Now, you might know this already, but here is the detail that trips up people: there are 2 ways to act as another user using JWT, and only one of them will give access to externally shared folders.
> 
> You already enabled both the permissions for this:
> 
> * Perform actions as users
> * Generate User Access Tokens
> 
> Only this second method can be used to access externally collaborated folders.
> 

Does the replacing of the code mean that I'm _using_ the generated user access token?
> In your code, replace
> 
> ```js
> const client = sdk.getAppAuthClient("enterprise")
> ```
> 
> with
> 
> ```js
> const client = sdk.getAppAuthClient("user", "[your_managed_user_id]")
> ```

**Comment by stephencweiss** [comment]
Answer: Yes. Yes, that's exactly what will happen :). 

Thanks again @cbetta! Looks like I'm all good now. 

May I ask though -- what did I miss in the guides / documentation that would have helped me understand this faster? (I spent ~ a week trying to build this app and have had a _really_ difficult time following the guides / understanding what was needed - so a lot of this progress was kind of blindly feeling my way through)

**Comment by cbetta** [comment]
@stephencweiss great to hear you figured this out. We are actively working currently on improving the guides, as well as the onboarding flow around these issues. A big problem we run into with out docs is that a lot of this is documented in some place, but many developers need a slightly different setup for different reasons. We're currently covering every use case with generic documentation, yet we're working on more in depth guides that get anyone started with just the code for their problem. I'm sorry to hear you got stuck this long, please ping me if you have any more issues.
