### ISSUE TITLE
How to set up App Auth Client?

### ISSUE THREAD

**Issue by pacific202** [box/box-node-sdk#516]
- [X ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

The SDK docs state:

> If you have a JSON configuration file from the Box Developer Console that includes your private key information, you can import that directly to create an SDK instance:

However, when I download the config file and import it I get an error:

> "clientID" must be set via init() before using the SDK

This seems to come from the SDK looking for a key of clientID, but the file I downloaded this morning stores this as boxAppSettings.clientID.  When I send in the boxAppSettings object into the SDK initialization function I then get this error:

> Key ID must be provided in app auth params

This can be fixed by changing the key "publicKeyID" in the config file to just "keyID", but then I get this error:

> Unexpected API Response [400 Bad Request] unauthorized_client - This app is not authorized by the enterprise admin

It seems like there are either some errors in the SDK or the docs here, as there's not enough info there for me to start using this auth method.  The Basic Client is working fine for me, but obviously is only adequate for the most basic initial tests.

### Expected Behavior
I would like to see some clear steps to set up App Auth without encountering multiple errors.

### Versions Used
Node SDK: 1.32.0

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by pacific202** [comment]
I started this thread in the forums too:

https://community.box.com/t5/Platform-and-Development-Forum/Config-issues-when-using-App-Auth-Client/td-p/84529

**Comment by sujaygarlanka** [comment]
@pacific202 I am not able to replicate your issue. It is working on my end. Are you sure you are running this code and are importing the correct JSON file into your code?
```
var BoxSDK = require('box-node-sdk');
var jsonConfig = require('/path/to/config.json');
var sdk = BoxSDK.getPreconfiguredInstance(jsonConfig);

var serviceAccountClient = sdk.getAppAuthClient('enterprise');
```

**Comment by pacific202** [comment]
I see the error came from not using getPreconfiguredInstance.
