### ISSUE TITLE
files.uploadNewFileVersion not resolving (time out)

### ISSUE THREAD

**Issue by stephencweiss** [box/box-node-sdk#518]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
When I attempt to upload a file (using an oauth2.0 w/ jwt) and it already exists, I want to fail back to uploading a new version. However, this is timing out (30+ seconds for a file that's 2.5kb)

### Steps to Reproduce
```
class BoxUploader {
  #boxClient;
  constructor(config) {
    this.#boxClient = this.#createBoxClient(config);
  }

  #createBoxClient = (config) => {
    const sdk = BoxSDK.getPreconfiguredInstance(config);
    const client = sdk.getAppAuthClient("user", USER_ID);
    return client;
  };
  /**
   * @argument {string} FolderId - the Box Folder ID to which the file will be uploaded
   * @argument {string} FileName - The name to be assigned to the new file
   * @argument {string | Buffer | Stream} File
   * @argument {boolean} [Version] - If true, will attempt to upload a new version
   * @returns {object} - The JSON response from Box
   */
  uploadFileToBox = async (folderId, fileName, file, version) => {
    try {
      return await this.#boxClient.files
        .uploadFile(folderId, fileName, file, version)
        .catch(async (err) => {
          if (version && err.response.body.status == 409) {
            console.log(`RETRY ATTEMPT`)
            const fileId = err.response.body.context_info.conflicts.id;
            const response =  await this.#boxClient.files.uploadNewFileVersion(fileId, file)
            .catch(err => console.error(`RETRY FAILED -> fileId is ${fileId}\n\tError: ${err}\n\tError Body${err.response.body}`))
            console.log(`RETRY SUCCESS -> ${response}`)
            return response
          } else {
            console.error(`ERROR DETAILS -> ${err}\n\tInvocation details ${JSON.stringify({folderId, fileName, file, version}, null, 4)}`);
            throw new Error(err);
          }
        });
    } catch (error) {
      throw new Error(error);
    }
  };
}
```

To be clear, I believe my use of the `uploadNewFileVersion` matches nicely with the example from the API documentation: 

![Screen Shot 2020-06-22 at 3 29 29 PM](https://user-images.githubusercontent.com/39878535/85332225-2f9e7380-b49d-11ea-8631-4a43188660df.png)

### Expected Behavior
If the file does _not_ exist, I expect the `uploadFile` to take over and succeed (it does).
If the file _does_ exist, I want it to fail over and upload a new version (it times out and fails).

### Error Message, Including Stack Trace
No error message - just a time out (I'm using an AWS Lambda)

### Screenshots
![Screen Shot 2020-06-22 at 3 27 45 PM](https://user-images.githubusercontent.com/39878535/85332114-f239e600-b49c-11ea-9fe6-4042b7f28ef6.png)

### Versions Used
Node SDK: `^1.32.0`

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by stephencweiss** [comment]
Tried refactoring it into its own function to more closely match the example - same result (still timing out):
```
class BoxUploader {
  #boxClient;
  constructor(config) {
    this.#boxClient = this.#createBoxClient(config);
  }

  #createBoxClient = (config) => {
    const sdk = BoxSDK.getPreconfiguredInstance(config);
    const client = sdk.getAppAuthClient("user", USER_ID);
    return client;
  };
  /**
   * @argument {string} FolderId - the Box Folder ID to which the file will be uploaded
   * @argument {string} FileName - The name to be assigned to the new file
   * @argument {string | Buffer | Stream} File
   * @argument {boolean} [Version] - If true, will attempt to upload a new version
   * @returns {object} - The JSON response from Box
   */
  uploadFileToBox = async (folderId, fileName, file, version) => {
    try {
      return await this.#boxClient.files
        .uploadFile(folderId, fileName, file, version)
        .catch(async (err) => {
          if (version && err.response.body.status == 409) {
            const fileId = err.response.body.context_info.conflicts.id;
            return await this.uploadNewFileVersion(fileId, file);
          } else {
            const message = `UPLOAD FAILED -> \n\t ERROR: ${err}\n\tDETAILS: ${JSON.stringify(
              { folderId, fileName, file, version },
              null,
              4
            )}`
            throw new Error(message);
          }
        });
    } catch (error) {
      throw new Error(error);
    }
  };

  uploadNewFileVersion = async (fileId, file) => {
    console.log(`RETRY ATTEMPT`);
    try {
      const result = await this.#boxClient.files.uploadNewFileVersion(fileId, file);
      console.log(`RETRY SUCCESSFUL`)
      return result
    } catch (err) {
      const message = (
        `RETRY FAILED -> fileId is ${fileId}\n\tError: ${err}\n\tError Body${err.response.body}`
      );
      throw new Error(message);
    }
  };
}
```

**Comment by PJSimon** [comment]
Hi @stephencweiss ,

Thanks for submitting this Issue! We will take a look and get back to you ASAP!

@PJSimon

**Comment by sujaygarlanka** [comment]
@stephencweiss Is this still an issue?

**Comment by stephencweiss** [comment]
@sujaygarlanka - honestly, haven't looked at DropBox in a few months as I'm in a new role.

**Comment by sujaygarlanka** [comment]
@stephencweiss Is it alright we close it? This seems like a code specific issue that we aren't able to replicate. If you need further help debugging this code, feel free to re-open this.

**Comment by leviplj** [comment]
I've got the same problem.
Version - "box-node-sdk": "^1.36.0"

**Comment by leviplj** [comment]
I've created the application and authorized it.
If I'm uploading the file 1st time, it works, but when I upload a second time and get to the fallback I get a time out.
If I comment the upload file part and leave just the upload new version with the manually set file id it also works.

The problem only occurs when I try to upload the file and right after upload a new version.

```js
configJson={
  "boxAppSettings": {
    "clientID": "REDACTED",
    "clientSecret": "REDACTED",
    "appAuth": {
      "publicKeyID": "REDACTED",
      "privateKey": "-----BEGIN ENCRYPTED PRIVATE KEY-----\nREDACTED\n-----END ENCRYPTED PRIVATE KEY-----\n",
      "passphrase": "REDACTED"
    }
  },
  "enterpriseID": "REDACTED"
}


var BoxSDK = require('box-node-sdk');
var fs = require('fs');

var sdk = BoxSDK.getPreconfiguredInstance(configJson);
var client = sdk.getAppAuthClient('user', 'REDACTED')

test = async () => {
  folderId = '0'

  var stream = fs.createReadStream('./Pizza.jpg');

  try {
    console.log('New File');
    b = await client.files.uploadFile(folderId, 'Pizza.jpg', stream)
  } catch (error) {
    console.log('error', JSON.stringify(error));
    if (error.statusCode === 409) {
      fileId = error.response.body.context_info.conflicts.id
      // fileId='XXXXXX' // Also tried setting the id manually
      console.log('New Version', fileId);
      
      try{
        c = await client.files.uploadNewFileVersion(fileId, stream)
        console.log(c);
      }catch (err) {
        console.log('error', JSON.stringify(err));
      }
    }
  }
}

test()
```

**Comment by leviplj** [comment]
Is is possible to reopen this issue?

**Comment by swfree** [comment]
Hi @leviplj,

Try creating a new stream to pass into the `uploadNewFileVersion` call, this worked for me when I tried to replicate the issue. It looks like the first stream is being closed when `uploadFile` fails.

So for your code snippet example, add this line before calling uploadNewFileVersion:
```
stream = fs.createReadStream('./Pizza.jpg');
c = await client.files.uploadNewFileVersion(fileId, stream)
```

@swfree

**Comment by leviplj** [comment]
@swfree Thanks, that worked.
