### ISSUE TITLE
Passing the body as an Object to validateWebhookMessage is not reliable

### ISSUE THREAD

**Issue by Avaq** [box/box-node-sdk#533]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

It was discovered via a recent Box Customer Success support ticket (`#2204084`) that using the object passing style implemented in #253 with `validateWebhookMessage` is not reliable.

The problem is that `JSON.parse` is lossy. The code added in #253\* assumes that `JSON.stringify(JSON.parse(x)) === x`, which is not always the case. For example:

```js
const x = '"\\/"';
JSON.stringify(JSON.parse(x)) !== x
```

This exact problem occurs when a webhook sends a message regarding an updated file. These messages include escaped characters, such as the one assigned to `x` in my example, and as such, are invalidated by `validateWebhookMessage` after having been JSON parsed.

\* The problematic code:

https://github.com/box/box-node-sdk/blob/f91ddc468aade7067c0aafa3ec4eb6944f2e911e/lib/managers/webhooks.js#L351-L355

### Versions Used
Node SDK: 1.33.0

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by PJSimon** [comment]
Hi @Avaq, 

Thanks for reporting this issue.  We are working on a fix now!

Thanks,

Patrick
