### ISSUE TITLE
box-node-sdk -->  using 'request' module which is deprecated.it's creating issue in my aws-sam project.

### ISSUE THREAD

**Issue by mansu1101** [box/box-node-sdk#537]
### Is your feature request related to a problem? Please describe.
I am using lambda serverless architecture and using AWS-SAM for building and deploying while building my project for deployment getting the issue. this issue is coming because of box-node-sdk using request module internally which is deprecated  https://github.com/request/request/issues/3142

### Additional context
It was working earlier because aws-sam was allowing to build with lower versions of nodejs. lower versions support the request module so there were no issue. But now aws-sam is not supported in nodejs lower versions so we need to upgrade nodejs version in my production.

Here is the error which  I am getting while build.
 $> sam build
Building function 'studentPaymentLambda'
Running NodejsNpmBuilder:NpmPack
Running NodejsNpmBuilder:CopyNpmrc
Running NodejsNpmBuilder:CopySource
Running NodejsNpmBuilder:NpmInstall

Build Failed
Error: NodejsNpmBuilder:NpmInstall - NPM Failed: npm WARN deprecated request@2.88.2: request has been deprecated, see htt
ps://github.com/request/request/issues/3142
npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! Error while executing:
npm ERR! C:\Users\mrtrived\AppData\Local\Programs\Git\cmd\git.EXE ls-remote -h -t ssh://git@bitbucket.org/gsucd/gs-deploy
.git
npm ERR!
npm ERR! git@bitbucket.org: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.

**Comment by coolaj86** [comment]
I have a secure, drop-in replacement for `request` available here:
https://github.com/therootcompany/request.js

I'm considering making a PR. It's a security vulnerability to have a dependency with hundreds of transitive dependencies to do what can be done in about 100 lines of code (even my library, at ~500 loc) is overkill.

Considering that wrapping an http request is the core value of the Box SDK... https://www.joelonsoftware.com/2001/10/14/in-defense-of-not-invented-here-syndrome/

Also, just plain node, no libraries:

```js
var https = require('https');

new Promise(function (resolve, reject) {
    var form = {
        from: 'mailer@example.com',
        'h:Reply-To': 'support@example.com',
        to: 'john.doe@gmail.com',
        subject: 'Hello',
        html: `${preHeader}<p>What's up?</p>`,
        text: "What's up?",
    };
    
    var buf = Buffer.from(querystring.stringify(form));

    var options = {
        hostname: 'api.mailgun.net',
        port: 443,
        path: `/v3/${domain}/messages`,
        method: 'POST',
        auth: `api:${apiKey}`,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded;charset=utf-8',
            'Content-Length': buf.byteLength
        }
    }

    const req = https.request(options, function (resp) {
        console.log("statusCode:", resp.statusCode);

        var body = '';
        resp.on('data', function(chunk) {
            body += chunk.toString('utf8');
        })
        resp.on('end', function () {
            resp.body = body;
            try {
                resp.body = JSON.parse(resp.body);
                resolve(resp.body);
            } catch(e) {
                e.response = resp;
                reject(e);
            }
        });
    })

    req.on('error', reject);
    req.write(buf);
    req.end();
});
```

From https://therootcompany.com/blog/send-email-with-mailgun-and-nodejs/.

**Comment by congminh1254** [comment]
Hi  @mansu1101 

We have just replace `request` library with `@cypress/request` and it fixes all the security issues.

Please check if it's working on your side now.

Best,
Minh
