### ISSUE TITLE
Getting an Embed Link

### ISSUE THREAD

**Issue by jmsherry** [box/box-node-sdk#54]
I can't see it in the docs, but does the SDK do this: https://docs.box.com/reference#get-embed-link ??

If not, can I add functions to the client to make that possible??

Thanks

**Comment by jmsherry** [comment]
https://github.com/box/box-node-sdk/pull/27/files/c65bd7c64a212a56c7f75e49da0e9999e8f3b336?diff=unified

Is still a work in progress??

**Comment by mattwiller** [comment]
@jmsherry This is already possible today using the basic `files.get()` call with the fields parameter, but as you mentioned there's a PR currently pending to add a convenience method.  To accomplish this today, you would do something like this:

```js
client.files.get(fileID, {fields: 'expiring_embed_link'}, function(err, data) {
    console.log(data.expiring_embed_link.url);
});
```

**Comment by jmsherry** [comment]
@mattwiller AH! Awesome!! Seems so easy now you point it out! 👍
