### ISSUE TITLE
Clarify what versioning scheme is followed

### ISSUE THREAD

**Issue by MartinJohns** [box/box-node-sdk#629]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

I haven't found any information regarding this in the README or in any other location, so I would like to ask for information what versioning scheme this package follows. I saw that the TypeScript migration (which is awesome! 🎉) was released as a patch version, but this package contains breaking changes due to changed dependencies and broke our builds. So I would assume this package does not follow SemVer.

I'm not entirely sure if this is due to changed dependencies, or just because the files are now picked up by TypeScript because they're TypeScript files. Regardless I would not have this release expected to be a patch update.

### Steps to Reproduce

1. Install version `1.37.0`.
2. Set version range to include patches: `~1.37.0`.
2. Receive the updated patch `1.37.1`.

### Expected Behavior

No breaking change.

### Error Message, Including Stack Trace

Build errors due to new dependencies:

> ../../node_modules/box-node-sdk/lib/api-request-manager.d.ts:5:23 - error TS2688: Cannot find type definition file for 'bluebird'.  
> /// \<reference types="bluebird" />

And many more alike.

### Versions Used
Node SDK: `1.37.0`

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by mhagmajer** [comment]
Hey @MartinJohns, thanks for creating the issue! We didn't intend for the latest patch release to have breaking change. I've verified that in-fact for TypeScript projects with `skipLibCheck` turned off the build was broken. We're doing another patch release with #630 to fix it.

**Comment by mhagmajer** [comment]
Here's the new release https://www.npmjs.com/package/box-node-sdk/v/1.37.2

**Comment by MartinJohns** [comment]
@mhagmajer I forgot to respond, so here it is: **Thank you** for the fast response and action!

So I understand you want to follow SemVer and avoid breaking changes and this was just a mistake. :-)
