### ISSUE TITLE
Enhance TS support for managers

### ISSUE THREAD

**Issue by jamie-box** [box/box-node-sdk#655]
### Is your feature request related to a problem? Please describe.
In `box-client.ts`, managers are imported and instantiated using es5 'require' and `var` syntax. This shortcut obviously works but developers lose TS/intellisense support/checking since this doesn't follow TS spec.

### Describe the solution you'd like
Manager imports should follow modern TS convention.

### Additional context
Fixes will be submitted via PR. I also included a fix for a callback on the generic `del` method making that callback an optional parameter for async support.

**Comment by jamie-box** [comment]
PR #656

**Comment by mhagmajer** [comment]
Thanks @jamie-box!
