### ISSUE TITLE
As-User support and optional passphrase

### ISSUE THREAD

**Issue by jonathanprl** [box/box-node-sdk#7]
Does this have As-User support? I can't seem to get it working using appAuth and setting the current user ID. I am getting a 403 Unauthorised error when getting the root folder for a user.

```
let sdk = new BoxSDK({
  clientID: box.clientId,
  clientSecret: box.clientSecret,
  appAuth: {
      keyID: box.publicKeyId,
      privateKey: box.RSAPrivate,
      passphrase: 000
  }
});

let adminAPIClient = sdk.getAppAuthClient('enterprise', box.enterpriseUserId);

adminAPIClient.CURRENT_USER_ID = '283606869';

adminAPIClient.folders.get('0', null, (err, users) => {
  logger.debug(users);
  logger.error(err);
});
```

I have a feeling it's due to our private key not having a passphrase. As looking at [line 111 in lib/util/config.js](https://github.com/box/box-node-sdk/blob/master/lib/util/config.js#L111) a passphrase is required.

**Comment by mattwiller** [comment]
In general, you should get a user app auth client for the app user you want to make calls as:

```js
let sdk = new BoxSDK({
  clientID: box.clientId,
  clientSecret: box.clientSecret,
  appAuth: {
      keyID: box.publicKeyId,
      privateKey: box.RSAPrivate,
      passphrase: 000
  }
});

let userAPIClient = sdk.getAppAuthClient('user', '283606869');

userAPIClient.folders.get('0', null, (err, users) => {
  logger.debug(users);
  logger.error(err);
});
```

Does that work for you?

**Comment by jonathanprl** [comment]
Yes that makes much more sense, thank you.
