### ISSUE TITLE
Auth Error: Please check the 'exp' claim. Should be an integer [400 Bad Request] invalid_grant - Please check the 'exp' claim. Should be an integer

### ISSUE THREAD

**Issue by Tiago-Altus** [box/box-node-sdk#713]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
When running my script which uses box-node-sdk to copy a file over to Box I get the issue:
Auth Error: Please check the 'exp' claim. Should be an integer [400 Bad Request] invalid_grant - Please check the 'exp' claim. Should be an integer
I am running a script that copies several hundred files over to box one after the other and this issue seemed to pop up randomly at first but now its consistently not letting me copy any files over to Box. 

Similar to this issue found here but the solution did not work for me:
https://support.box.com/hc/en-us/community/posts/360049181453-Getting-Please-check-the-exp-claim-Exception

### Expected Behavior
For the file to successfully be copied over to Box

### Error Message, Including Stack Trace
(node:17496) UnhandledPromiseRejectionWarning: Error: Auth Error: Please check the 'exp' claim. Should be an integer [400 Bad Request] invalid_grant - Please check the 'exp' claim. Should be an integer
    at Object.buildResponseError (C:\Users\32482\OneDrive\Desktop\fsxConcurrentProcesses\migration3\node_modules\box-node-sdk\src\util\errors.ts:125:40)

### Versions Used
Node SDK: "box-node-sdk": "^2.0.0"

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by lukaszsocha2** [comment]
Hi @Tiago-Altus,
Thanks for submitting this Issue! We will take a look and get back to you ASAP!
@lukaszsocha2

**Comment by lukaszsocha2** [comment]
Hi @Tiago-Altus,
thanks again for reporting the bug. It should be fixed now with the linked pr. It should be released with the next release, which is planned for the next week.
@lukaszsocha2
