### ISSUE TITLE
enhance uploadFile interface (typescript)

### ISSUE THREAD

**Issue by huineng** [box/box-node-sdk#729]
box 

Hi, i refer to this file and line https://github.com/box/box-node-sdk/blob/f0c0135511fde46144e6c496432104321af443f6/src/managers/files.ts#L744

it describes the interface to upload a file , name the options parts (previously Record<string, any>) now

```
{
    content_created_at?: string;
    content_modified_at?: string;
    content_length?: number;
}
```

can you please add description as that is an options field that can be posted with the upload

thanks

```
{
    content_created_at?: string;
    content_modified_at?: string;
    content_length?: number;
    description?: string

}
```

**Comment by arjankowski** [comment]
Hi @huineng,

We have already added `description` field as you asked. 
In the next few weeks we will release this change with new version.

@arjankowski
