### ISSUE TITLE
Create a new v3.x for node v18.x+

### ISSUE THREAD

**Issue by coolaj86** [box/box-node-sdk#781]
### Is your feature request related to a problem? Please describe.

Stack traces that originate from Box are terrible (they go into hundreds of lines of Bluebird and stop).

There's also lots of _very_ old deprecated code.

There's also various vectors for attack due to the myriad of dependencies.

### Describe the solution you'd like

A new version that keeps the same API, but that uses all that's available in node v18.x+ (because a lot of good things were added in v18, like crypto.subtle) that make compatibility, security, and dependency issues better.

### Describe alternatives you've considered

Build my own Box SDK from scratch for the half-dozen endpoints I need.

### Additional context

I'd love to work with you as a 1099 to create a refactored version that uses native `Promise`s, native `https` (wrapped in about 500 lines to be compatible with `request` and minimize code changes), and other native code in order to drop dependencies and improve debuggability.

Minimal changes, passing the same tests, just dropping node v4.x support in favor of the upcoming LTS version.

**Comment by arjankowski** [comment]
Hi @coolaj86 ,
Thank you for your feedback and your support!

We actually have a plan to refresh the node sdk in the near future.
So keep an eye on this repository so you don't miss any news.

Regards,
Artur

**Comment by coolaj86** [comment]
> near future

🧐 hasn't that been the plan for about 2 years now... ?

If you don't have the capacity to get it into the schedule, contract it out. I'd introduce no new dependencies and make very clean PRs. I'm sure you can find some other high-yield talent from you user base.

I mean, if it's actually in the schedule for 2023 Q1 and it's actually scoped out in a way that can be accomplished in 2 weeks, then great.

But if you've got to rewrite your code generator to do a refresh across 6 different languages... we both know that's never actually going to make priority to get done. #amiright?

**Comment by michaelhays** [comment]
@arjankowski Are there any updates about the next version of `box-node-sdk`?

I saw @lukaszsocha2 mention [here](https://github.com/box/box-node-sdk/issues/788#issuecomment-1366696645) that there was a beta version in the works that was planned to be released by the end of April. Curious if that beta is still being worked on.

**Comment by congminh1254** [comment]
Hi @michaelhays 

For the version 3.0 which contains some dependencies upgrades, and some small features, ... will be released around the end of May / June.

About the next generation of Node SDK, which separate with this Node SDK, we will release the beta version for testing purpose.

Best,
Minh

**Comment by congminh1254** [comment]
Hi @coolaj86 

We have just released version 3.0 of the Box Node SDK. But we only support Node version from 12 to 16 for now.

Best regards,
Minh

**Comment by michaelhays** [comment]
Hi @congminh1254, is this latest release supposed to include the dependencies upgrades? I noticed the 3.0.0 version still depends on [`request`](https://github.com/box/box-node-sdk/blob/9ea993146ba6f1ea9f829e3a968a7639f45d292e/package.json#L46) (which has been deprecated for 4 years now) and a dangerously outdated version of [`uuid`](https://github.com/box/box-node-sdk/blob/9ea993146ba6f1ea9f829e3a968a7639f45d292e/package.json#L48).

I'd love to get rid of these warnings whenever I install the dependencies in my project:

```
 WARN  deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

**Comment by congminh1254** [comment]
Hi @michaelhays 

I will try to bump the version for the `uuid` package. By the time, we are working on the next generation of Box Node SDK, which will use `axios` instead, I think we are not going to replace `request` with another library until then.

Thanks for your understanding.

Best,
Minh

**Comment by michaelhays** [comment]
Excellent, thanks y'all!

**Comment by congminh1254** [comment]
Hi,

With the pull request #836, we fixed the compatibility with Node version 18 and 20. 

Best,
Minh

**Comment by michaelhays** [comment]
Thanks so much @congminh1254!

Just migrated to `box-typescript-sdk-gen`, pretty much everything went seamlessly :) Thrilled to have full type coverage!

**Comment by dtto86** [comment]
Thanks @congminh1254 for `box-typescript-sdk-gen` beta release.

In our Production NodeJs app, currently we are on `box-node-sdk@^2.x.x` and due to deprecation of `request`, `har-validator` & `uuid` dependencies used in v2.x.x, we eagerly wanted to upgrade to v3.x.x.

So, is there any plan to release stable v3.x.x in next 2 - 3 months?

Again, thanks for your work!!

**Comment by mgrytsai** [comment]
It's a matter of a few months to have first stable version of `box-typescript-sdk-gen`. We are currently collecting feedback (you are welcome to make suggestions). We aim to have a stable version by the end of December-January 2024.

**Comment by congminh1254** [comment]
Hi @coolaj86 

We have just replace request library with @cypress/request and it fixes all the security issues.

Please check if it's working on your side now.

Best,
Minh

**Comment by echarpibm** [comment]
> We have just replace request library with @cypress/request and it fixes all the security issues.
> 
> Please check if it's working on your side now.
> 

Finally! And yes it seems to work.
