### ISSUE TITLE
request har-validator and uuid are deprecated now, is there any plan to move away from request har-validator and uuid or to replace request har-validator and uuid

### ISSUE THREAD

**Issue by Ashwini02-Ghaytad** [box/box-node-sdk#788]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue. 
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x]  I have searched [Issues in this repo][github-repo] and my issue isn't already reported.
 

While analyzing a issue we observed that `box-node-sdk` is pulling `request` `har-validator` and `uuid` , all 3 modules are deprecated now, is there any plan to move away from `request` `har-validator` and `uuid` or to replace ` request` `har-validator` and `uuid`.

            └─┬ box-node-sdk@2.8.0
                 └─┬ request@2.88.2
                      └── har-validator@5.1.5
	
             ├─┬ box-node-sdk@2.8.0
             │   ├─┬ request@2.88.2
             │   │   └── uuid@3.4.0
             │   └── uuid@3.4.0

**Comment by lukaszsocha2** [comment]
Hi @Ashwini02-Ghaytad,
we are currently working on next-gen Node SDK, which will not use request library any more and will use completely new network library. The plan is to release it in the first half of the next year. Please keep up to date with our announcements to have a grip on it.
Best,
@lukaszsocha2

**Comment by Ashwini02-Ghaytad** [comment]
Hi @lukaszsocha2 
Could you give us more insights on timeline we are looking at for release of next-gen Node SDK? First half of 2023 will be slightly broader timeline to consider.

**Comment by mhagmajer** [comment]
@Ashwini02-Ghaytad if you share what features (modules) of the SDK you're currently using we could include you in the beta program on the new SDK, therefore making it available for you sooner

**Comment by lukaszsocha2** [comment]
First beta version is planned to be released by the end of April, but it will not include all endpoints
