### ISSUE TITLE
Will the userClient of an admin account be able to retrieve all files and folders by iterating from root folder "0"? 

### ISSUE THREAD

**Issue by deva-pingsafe** [box/box-node-sdk#799]
I basically want to get the file and folder properties (like file name, shared links e.t.c). I don't want to retrieve or download the file/folder itself. So do i have to create userClient of each user in the enterprise and then recursively iterate from root folder 0 or will any one userClient be able to retrieve this data? (Assuming the app i created has the permissions to read this data)

**Comment by lukaszsocha2** [comment]
Hi @deva-pingsafe,
there is `as-User` feature, which allows enterprise admins to make API calls on behalf of their enterprise's users. Documentation and example how to use it can be found [here](https://github.com/box/box-node-sdk/blob/main/docs/authentication.md#as-user). If you have any further questions, let us know.
Best,
@lukaszsocha2

**Comment by deva-pingsafe** [comment]
Hi lukas, thanks for the response. So without using the "as-user" feature. If i create a userClient of an admin user using
`var userClient = boxSDK.getAppAuthClient('user', user.id)`

and then if i use this userClient to fetch folder info like this:

`userClient.folders.getItems('0')`

will it only fetch the items owned by the original admin user? or all users?

**Comment by lukaszsocha2** [comment]
Hi @deva-pingsafe,
in the case you described you would get only items of the original admin user. To get other user files you must use as-user feature.
Best,
@lukaszsocha2

**Comment by deva-pingsafe** [comment]
Thanks for the information, lukas
