### ISSUE TITLE
How to report security issue privately?

### ISSUE THREAD

**Issue by claritypotion** [box/box-node-sdk#810]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

Hey, can't find `security.md`. How do I report an active issue with credential leakage? Don't want to make it public.

**Comment by congminh1254** [comment]
Hi @claritypotion 

If you have any security issues and need to send information privately, I would suggest reaching out to support at https://developer.box.com/support/

The support team will analyze the problem and escalate it to the proper teams if needed.

Best regards,
Minh
