### ISSUE TITLE
Query by metadata has incorrect options

### ISSUE THREAD

**Issue by swanysimon** [box/box-node-sdk#877]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

The [query by metadata function](https://github.com/box/box-node-sdk/blob/v3.5.0/src/managers/metadata.ts#L400) is not correct and will always result in a 400 Bad Request if `query_parameters` are supplied. Specifically, the `query_parameters` options should be `query_params`, and `order_by` should be optional. In addition there are missing options: `limit` and `marker`.

API Reference: https://developer.box.com/reference/post-metadata-queries-execute-read/

### Steps to Reproduce

An example:

```javascript
    const options = {
      fields: ["id", "name", "sha1"],
      query: "myMetadataIdField = :id",
      query_parameters: {id: "my_special_id"},
      order_by: {},
    };
    return this.client.metadata.query(
      "enterprise_scope.metadataTemplateKey",
     "123",
      options,
    );
```

And you receive a:

`Error: Unexpected API Response [400 Bad Request | ...] invalid_query - Parameter id: no value provided`

(I actually got this error after removing the `order_by` field because before that, you don't even get a reason for why the request was bad, you just get a 400)

### Expected Behavior

To receive a 200 response and my matching files.

### Workaround

Forcibly ignore the type mismatch.

```javascript
    const options = {
      fields: ["id", "name", "sha1"],
      query: "myMetadataIdField = :id",
      query_params: {id: "my_special_id"},
    };
    return this.client.metadata.query(
      "enterprise_scope.metadataTemplateKey",
     "123",
      // @ts-expect-error: option type definition for metadata query is incorrect
      options,
    );
```

### Error Message, Including Stack Trace

I'd rather not redact, and this seems pretty straightforward.

### Screenshots

n/a

### Versions Used

Node SDK: 3.1.1 and 3.5.0

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-node-sdk/search?type=Issues

**Comment by arjankowski** [comment]
Hi @swanysimon,
We've just released the new version of box-node-sdk, `3.5.1`, with the fix to the bug you mentioned.

Regards,
Artur
