### ISSUE TITLE
"Search for Metadata" always results in bad request

### ISSUE THREAD

**Issue by mjanathk** [box/box-node-sdk#90]
It looks like there is a bug in the SDK when we "search for metadata" as described in the document ( _https://github.com/box/box-node-sdk/blob/144dd852bcf8e6c511b0141c08b635902dabd8db/docs/search.md)._ Pls see below
**Code:**
_userAPIClient.search.query( 
'', 
{ 
'file_extensions': 'ppt,pptx', 
'mdfilters': [ 
{ 
'templateKey': 'TopSecret', 
'scope': 'enterprise', 
'filters': {} 
} 
] 
}, 
function(err,response){ 
console.log(err,response); 
res.json(err); 
});_
**Error:**
_{ type: 'error', 
status: 400, 
code: 'bad_request', 
help_url: 'http://developers.box.com/docs/#errors', 
message: 'Bad Request', 
request_id: '856959801583385d32e9c2' } } }_

**PS: The basic SDK search works fine (code below).**
_userAPIClient.search.query('teamLogo1.png',null,function(err,response){ 
res.json(response);
});_

**Comment by mattwiller** [comment]
@mjanathk Thanks for catching this!  The default query stringification wasn't correctly handling the mdfilters parameter; I'll have a fix ready by the end of today.

**Comment by mjanathk** [comment]
Thanks Matt
